In [4607]:
# تحميل المكتبات الأساسية
import pandas as pd
import numpy as np

# مكتبة التعامل مع البيانات المفقودة وتوحيد القيم
from sklearn.impute import SimpleImputer
# مكتبة لتنظيف البيانات وتعديل الأعمدة
import re

In [4608]:
sales_transactions = pd.read_csv('Sales_Transactions.csv')
store_information = pd.read_csv('Store_Information.csv')
customer_data = pd.read_csv('Customer_Data.csv')
marketing_campaigns = pd.read_csv('Marketing_Campaigns.csv')
store_complaints = pd.read_csv('Store_Complaints.csv')

In [4609]:
# check the data shape
print(sales_transactions.shape)

(25375, 8)

In [4610]:
# استعراض أول 5 صفوف
sales_transactions.head()
#اكتشفت فيه قيم سالبه في الايرادات اما مرتجعات او خطا في الادخال  
# لكن لن اعتبرها مرتجعات لان كل قيم الوحدات المباعه بالموجب ايضا لاتعتبر دفع اجل او دين
#  لانه بعض الايرادات السالبه ليس لها كستمر اي دي

,Transaction_ID,Store_ID,Date,Product_Category,Units_Sold,Revenue,Discount_Percentage,Customer_ID
0,TXN023368,STORE_027,20/05/2024,Electronics,9,"-1,794",15,CUST00836
1,TXN004823,STORE_039,19/04/2023,Home & Garden,11,373,5,CUST06683
2,TXN024939,STORE_029,2023-03-04,Food & Beverage,4,"4,268",15,CUST03565
3,TXN015257,STORE_033,06/03/2024,Electronics,39,"4,325",0,CUST07318
4,TXN024609,STORE_021,2023-05-30,Electronics,42,"4,409",0,CUST07210

In [4611]:
# عرض معلومات عن الأعمدة
sales_transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25375 entries, 0 to 25374
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Transaction_ID       25375 non-null  object
 1   Store_ID             25375 non-null  object
 2   Date                 25375 non-null  object
 3   Product_Category     25375 non-null  object
 4   Units_Sold           25375 non-null  int64
 5   Revenue              25375 non-null  float64
 6   Discount_Percentage  25375 non-null  int64
 7   Customer_ID          23344 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 1.5+ MB

In [4612]:
# تحليل القيم المفقودة في الأعمدة
sales_transactions.isnull().sum()

Transaction_ID            0
Store_ID                  0
Date                      0
Product_Category          0
Units_Sold                0
Revenue                   0
Discount_Percentage       0
Customer_ID            2031
dtype: int64

In [4613]:
pd.options.display.float_format = '{:,.0f}'.format

# إحصائيات وصفية عن البيانات الرقمية
sales_transactions.describe()

       Units_Sold  Revenue  Discount_Percentage
count      25,375   25,375               25,375
mean           25    2,537                    9
std            15    2,885                    9
min             1   -4,989                    0
25%            13    1,225                    0
50%            25    2,504                   10
75%            37    3,742                   15
max           240   98,062                   30

In [4614]:
# التحقق من وجود مسافات فارغة فقط في الأعمدة النصية
whitespace_rows = sales_transactions[sales_transactions.select_dtypes(include=['object']).apply(lambda x: x.str.contains('^\s*$', na=False)).any(axis=1)]

# عرض الصفوف التي تحتوي على مسافات فارغة في الأعمدة النصية
print("\nRows with White Spaces in Any Text Column:")
print(whitespace_rows)

Rows with White Spaces in Any Text Column:
Empty DataFrame
Columns: [Transaction_ID, Store_ID, Date, Product_Category, Units_Sold, Revenue, Discount_Percentage, Customer_ID]
Index: []

In [4615]:
# عرض القيم الفريدة في عمود Product_Category
sales_transactions['Product_Category'].unique()

array(['Electronics', 'Home & Garden', 'Food & Beverage', 'Beauty',
       'Clothing', 'Sports'], dtype=object)

In [4616]:
# اتضح عندنا قيم مفقوده في customer ID 
# وايضا قيم بالسالب في Revenue 
#لن نحذف صفوف الي فيها قيم مفقوده للكستمر اي دي لاننا كذا بنخسر 8% من بيانات المبيعات بدون سبب ولايهمني الان تحليل يخص العميل 
#صيغ التاريخ ليست موحده
#هنالك 375 صف مكرر في 	Transaction_ID ببعض الفروق في الايردات فروق في الكسور ايضا في الكستمر اي دي بعضها فيه nan

In [4617]:
# تحويل العمود Date إلى نوع datetime مع توحيد الصيغ في DataFrame الصحيح
sales_transactions['Date'] = pd.to_datetime(sales_transactions['Date'], errors='coerce')

C:\Users\POWER\AppData\Local\Temp\ipykernel_35936\3307575795.py:2: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  sales_transactions['Date'] = pd.to_datetime(sales_transactions['Date'], errors='coerce')

In [ ]:

# التحقق من وجود تواريخ قبل 2023 أو بعد يونيو 2024
invalid_dates = sales_transactions[(sales_transactions['Date'] < '2023-01-01') | (sales_transactions['Date'] > '2024-06-30')]

# عرض التواريخ غير المتوافقة
print(f"Number of rows with invalid dates: {invalid_dates.shape[0]}")
print(invalid_dates[['Transaction_ID', 'Date']].head())

# عرض أقدم وأحدث تاريخ
earliest_date = sales_transactions['Date'].min()
latest_date = sales_transactions['Date'].max()

print(f"\nEarliest Date in the data: {earliest_date}")
print(f"Latest Date in the data: {latest_date}")
#بملف التعليمات مكتوب ان البيانات من 
#2023 يناير الى 2024 يونيو
# هنا تظهر 493 عمليه خارج هذه المده 
#قررت ابقي على هذه البيانات لانها تدعم القرار

Number of rows with invalid dates: 493
    Transaction_ID       Date
14       TXN009718 2024-08-05
120      TXN022087 2024-08-06
152      TXN016199 2024-07-04
195      TXN003762 2024-07-02
213      TXN014862 2024-11-01

Earliest Date in the data: 2023-01-01 00:00:00
Latest Date in the data: 2024-12-06 00:00:00

In [4619]:
# تحويل جميع القيم السلبية في Revenue إلى قيم موجبة
sales_transactions['Revenue'] = sales_transactions['Revenue'].abs()

# عرض أول 5 صفوف بعد التعديل للتأكد
print("\nSales Transactions (After Making Revenue Positive):")
sales_transactions.head()
# #حولناها لموجب ولم نعتبرها مرتجعات لان ماعندي المعلومه الكافيه اذا كان مرتجع ام لا 
# وكذلك هدفي معرفة اين افضل 5 مناطق للفتح فيها والمرتجعات لاتهمنا الان 
#يهمنا الان كم اجمالي الايرادات وليست الارباح

Sales Transactions (After Making Revenue Positive):

,Transaction_ID,Store_ID,Date,Product_Category,Units_Sold,Revenue,Discount_Percentage,Customer_ID
0,TXN023368,STORE_027,2024-05-20,Electronics,9,"1,794",15,CUST00836
1,TXN004823,STORE_039,2023-04-19,Home & Garden,11,373,5,CUST06683
2,TXN024939,STORE_029,2023-03-04,Food & Beverage,4,"4,268",15,CUST03565
3,TXN015257,STORE_033,2024-06-03,Electronics,39,"4,325",0,CUST07318
4,TXN024609,STORE_021,2023-05-30,Electronics,42,"4,409",0,CUST07210

In [4620]:
# التحقق من التكرار في Transaction_ID
duplicate_transactions = sales_transactions[sales_transactions.duplicated(subset='Transaction_ID', keep=False)]


duplicate_transactions.head(10)

# تحديد الصفوف المكررة بناءً على Transaction_ID

,Transaction_ID,Store_ID,Date,Product_Category,Units_Sold,Revenue,Discount_Percentage,Customer_ID
4,TXN024609,STORE_021,2023-05-30,Electronics,42,"4,409",0,CUST07210
19,TXN004269,STORE_018,2024-02-04,Clothing,26,123,15,CUST00906
34,TXN019979,STORE_045,2023-05-06,Electronics,19,"1,756",10,CUST00691
100,TXN002433,STORE_044,2024-05-26,Sports,39,"2,994",20,CUST06467
143,TXN023878,STORE_042,2024-01-08,Home & Garden,48,"2,073",10,CUST04039
148,TXN023358,STORE_031,2023-03-21,Beauty,22,"2,949",0,CUST07246
158,TXN018764,STORE_041,2023-08-10,Beauty,2,655,25,CUST00191
171,TXN011504,STORE_008,2023-10-07,Clothing,14,"4,567",0,CUST02684
244,TXN004458,STORE_042,2023-07-20,Beauty,38,"3,923",10,CUST06007
393,TXN021358,STORE_016,2023-01-09,Home & Garden,28,"1,147",5,CUST01691

In [4621]:
# حساب عدد القيم الفريدة في Transaction_ID
unique_transaction_ids = sales_transactions['Transaction_ID'].nunique()

# عرض عدد القيم الفريدة
print(f"عدد القيم الفريدة في Transaction_ID: {unique_transaction_ids}")

عدد القيم الفريدة في Transaction_ID: 25000

In [4622]:
#نشوف اذا متكرر الادخال او هنالك اختلاف في الاعمده الثانيه لل375 صف متكرر من Transaction_ID  
# التحقق من الصفوف المكررة في جميع الأعمدة
duplicate_rows = sales_transactions[sales_transactions.duplicated(keep=False)]

# عرض الصفوف المتكررة
print("Duplicate Rows (Exact Matches in All Columns):")
print(duplicate_rows)

Duplicate Rows (Exact Matches in All Columns):
Empty DataFrame
Columns: [Transaction_ID, Store_ID, Date, Product_Category, Units_Sold, Revenue, Discount_Percentage, Customer_ID]
Index: []

In [4623]:
#  حساب عدد تكرار كل Transaction_ID
transaction_counts = sales_transactions['Transaction_ID'].value_counts()

# عرض عدد التكرار لكل Transaction_ID
print("Transaction_ID Counts (How many times each ID appears):\n", transaction_counts)
print("\n max repetaions",transaction_counts.max())
#نتاكد انه لم يتكرر اكثر من مره فطلع لنا التكرار مره واحده

Transaction_ID Counts (How many times each ID appears):
 TXN003495    2
TXN006479    2
TXN015451    2
TXN016393    2
TXN001910    2
TXN003733    2
TXN016975    2
TXN008501    2
TXN014048    2
TXN002541    2
TXN007204    2
TXN023708    2
TXN006962    2
TXN005918    2
TXN003927    2
TXN012516    2
TXN016651    2
TXN003816    2
TXN008771    2
TXN013452    2
TXN022876    2
TXN002549    2
TXN000606    2
TXN010001    2
TXN008409    2
TXN023026    2
TXN003741    2
TXN018432    2
TXN021109    2
TXN003971    2
TXN013356    2
TXN001375    2
TXN011565    2
TXN024808    2
TXN007263    2
TXN001527    2
TXN018297    2
TXN014242    2
TXN016842    2
TXN006018    2
TXN017009    2
TXN001186    2
TXN007231    2
TXN018345    2
TXN024066    2
TXN009480    2
TXN011837    2
TXN009691    2
TXN017078    2
TXN023318    2
TXN009622    2
TXN023271    2
TXN019470    2
TXN015908    2
TXN023832    2
TXN010718    2
TXN013014    2
TXN019195    2
TXN010480    2
TXN015152    2
TXN003207    2
TXN009387    2
TXN013233    2
TXN000834    2
TXN023611    2
TXN021748    2
TXN004397    2
TXN008176    2
TXN005924    2
TXN008802    2
TXN011852    2
TXN010535    2
TXN000987    2
TXN022338    2
TXN008461    2
TXN021861    2
TXN003809    2
TXN013517    2
TXN005400    2
TXN016474    2
TXN010007    2
TXN008481    2
TXN015872    2
TXN020516    2
TXN000203    2
TXN010599    2
TXN011095    2
TXN012125    2
TXN001115    2
TXN004411    2
TXN015905    2
TXN017240    2
TXN007043    2
TXN009829    2
TXN003740    2
TXN016426    2
TXN015704    2
TXN010538    2
TXN003041    2
TXN005142    2
TXN017648    2
TXN024993    2
TXN007716    2
TXN007604    2
TXN009621    2
TXN009071    2
TXN001109    2
TXN023526    2
TXN000055    2
TXN019570    2
TXN013422    2
TXN011855    2
TXN010254    2
TXN005269    2
TXN021358    2
TXN024721    2
TXN006021    2
TXN018196    2
TXN004516    2
TXN015834    2
TXN008385    2
TXN024845    2
TXN014166    2
TXN012244    2
TXN013880    2
TXN018197    2
TXN002380    2
TXN019104    2
TXN021632    2
TXN012088    2
TXN016725    2
TXN023549    2
TXN017540    2
TXN021035    2
TXN024727    2
TXN023264    2
TXN015648    2
TXN020682    2
TXN007387    2
TXN002830    2
TXN007339    2
TXN010789    2
TXN021712    2
TXN003457    2
TXN000416    2
TXN007045    2
TXN016171    2
TXN007482    2
TXN011840    2
TXN003171    2
TXN003667    2
TXN001173    2
TXN024289    2
TXN000204    2
TXN010982    2
TXN000786    2
TXN022948    2
TXN004881    2
TXN019079    2
TXN012389    2
TXN023302    2
TXN023721    2
TXN018094    2
TXN001335    2
TXN000746    2
TXN024731    2
TXN001893    2
TXN021406    2
TXN022758    2
TXN019839    2
TXN007748    2
TXN006283    2
TXN006056    2
TXN016662    2
TXN021193    2
TXN013842    2
TXN010393    2
TXN015289    2
TXN018932    2
TXN014969    2
TXN005025    2
TXN015615    2
TXN024189    2
TXN011675    2
TXN020951    2
TXN018356    2
TXN008331    2
TXN024683    2
TXN017566    2
TXN021011    2
TXN015942    2
TXN016629    2
TXN013844    2
TXN023107    2
TXN001174    2
TXN000870    2
TXN004401    2
TXN022125    2
TXN004524    2
TXN021493    2
TXN002387    2
TXN008672    2
TXN000874    2
TXN011038    2
TXN015338    2
TXN006609    2
TXN001117    2
TXN024921    2
TXN007176    2
TXN019492    2
TXN018460    2
TXN002263    2
TXN009388    2
TXN015266    2
TXN017312    2
TXN024685    2
TXN021934    2
TXN007143    2
TXN000859    2
TXN009087    2
TXN006336    2
TXN012990    2
TXN018130    2
TXN023540    2
TXN020659    2
TXN007677    2
TXN010496    2
TXN019018    2
TXN011764    2
TXN004767    2
TXN010136    2
TXN006337    2
TXN004354    2
TXN002236    2
TXN013478    2
TXN006510    2
TXN022150    2
TXN009521    2
TXN006802    2
TXN015739    2
TXN017006    2
TXN022565    2
TXN010581    2
TXN017498    2
TXN010619    2
TXN013995    2
TXN022461    2
TXN015621    2
TXN014905    2
TXN015692    2
TXN006326    2
TXN007300    2
TXN008673    2
TXN018396    2
TXN009952    2
TXN019049    2
TXN007597    2
TXN015297    2
TXN016175    2
TXN009740    2
TXN003965    2
TXN004849    2
TXN022886    2
TXN016791    2
TXN023174    2
TXN012749    2
TXN000574    2
TXN016027    2
TXN019090    2
TXN005871    2
TXN006215    2
TXN004092    2
TXN017169    2
TXN003943    2
TXN022819    2
TXN009591    2
TXN008431    2
TXN006602    2
TXN019712    2
TXN018881    2
TXN007402    2
TXN005664    2
TXN016294    2
TXN001330    2
TXN014586    2
TXN002257    2
TXN001446    2
TXN012772    2
TXN007116    2
TXN011543    2
TXN005183    2
TXN021177    2
TXN016563    2
TXN015167    2
TXN018649    2
TXN019112    2
TXN019824    2
TXN012293    2
TXN011238    2
TXN018814    2
TXN000653    2
TXN018159    2
TXN006224    2
TXN013684    2
TXN024027    2
TXN006663    2
TXN000364    2
TXN015011    2
TXN013829    2
TXN015041    2
TXN002468    2
TXN021923    2
TXN012627    2
TXN008150    2
TXN017844    2
TXN004233    2
TXN011504    2
TXN020172    2
TXN010835    2
TXN005758    2
TXN003479    2
TXN004458    2
TXN023878    2
TXN016762    2
TXN010545    2
TXN018422    2
TXN009979    2
TXN010460    2
TXN016112    2
TXN018442    2
TXN007321    2
TXN000098    2
TXN020415    2
TXN004042    2
TXN014258    2
TXN021734    2
TXN021036    2
TXN005741    2
TXN014821    2
TXN002433    2
TXN016124    2
TXN001490    2
TXN024168    2
TXN000444    2
TXN005347    2
TXN011470    2
TXN016387    2
TXN004269    2
TXN002191    2
TXN012940    2
TXN018893    2
TXN003853    2
TXN017384    2
TXN014031    2
TXN015332    2
TXN018083    2
TXN020051    2
TXN007911    2
TXN023241    2
TXN005446    2
TXN023358    2
TXN020071    2
TXN010902    2
TXN015138    2
TXN007309    2
TXN021247    2
TXN004322    2
TXN003992    2
TXN019008    2
TXN014337    2
TXN018764    2
TXN010302    2
TXN019979    2
TXN018262    2
TXN024609    2
TXN005971    1
TXN019396    1
TXN003902    1
TXN021938    1
TXN022432    1
TXN016430    1
TXN007380    1
TXN000320    1
TXN020170    1
TXN024518    1
TXN003866    1
TXN014064    1
TXN019551    1
TXN021113    1
TXN012226    1
TXN015681    1
TXN023527    1
TXN020149    1
TXN017457    1
TXN023535    1
TXN010511    1
TXN024016    1
TXN014162    1
TXN002970    1
TXN016685    1
TXN018816    1
TXN018052    1
TXN003639    1
TXN015674    1
TXN002294    1
TXN000567    1
TXN001931    1
TXN014104    1
TXN007721    1
TXN021830    1
TXN001020    1
TXN003903    1
TXN016547    1
TXN001235    1
TXN015868    1
TXN008299    1
TXN020582    1
TXN018732    1
TXN024415    1
TXN015284    1
TXN010019    1
TXN014822    1
TXN016831    1
TXN004777    1
TXN019616    1
TXN006610    1
TXN011076    1
TXN001966    1
TXN017003    1
TXN018063    1
TXN006116    1
TXN015557    1
TXN013350    1
TXN014838    1
TXN024412    1
TXN017965    1
TXN012406    1
TXN011203    1
TXN018037    1
TXN000468    1
TXN018406    1
TXN023915    1
TXN008739    1
TXN018993    1
TXN010491    1
TXN010827    1
TXN004274    1
TXN009732    1
TXN020852    1
TXN014231    1
TXN014742    1
TXN020223    1
TXN020971    1
TXN004774    1
TXN013601    1
TXN022032    1
TXN019736    1
TXN015951    1
TXN018541    1
TXN009152    1
TXN004730    1
TXN007198    1
TXN017073    1
TXN022530    1
TXN009867    1
TXN003409    1
TXN007285    1
TXN016041    1
TXN005066    1
TXN009260    1
TXN005536    1
TXN016502    1
TXN002792    1
TXN000709    1
TXN019080    1
TXN024563    1
TXN011170    1
TXN009512    1
TXN013287    1
TXN022958    1
TXN013903    1
TXN006847    1
TXN000820    1
TXN003683    1
TXN009820    1
TXN009442    1
TXN007556    1
TXN023814    1
TXN015466    1
TXN009903    1
TXN004359    1
TXN018832    1
TXN018754    1
TXN009676    1
TXN014638    1
TXN020733    1
TXN000750    1
TXN006612    1
TXN022895    1
TXN005189    1
TXN013777    1
TXN008349    1
TXN014188    1
TXN001008    1
TXN018225    1
TXN016241    1
TXN000351    1
TXN022199    1
TXN015058    1
TXN016494    1
TXN002531    1
TXN007841    1
TXN013084    1
TXN002223    1
TXN023962    1
TXN016129    1
TXN018752    1
TXN003167    1
TXN015427    1
TXN015926    1
TXN002442    1
TXN010155    1
TXN022626    1
TXN006693    1
TXN010363    1
TXN006566    1
TXN012609    1
TXN023502    1
TXN005422    1
TXN008967    1
TXN017569    1
TXN005448    1
TXN007475    1
TXN022668    1
TXN009717    1
TXN018632    1
TXN011277    1
TXN015045    1
TXN010432    1
TXN005344    1
TXN014017    1
TXN000061    1
TXN011488    1
TXN007093    1
TXN018167    1
TXN005314    1
TXN004871    1
TXN020218    1
TXN001904    1
TXN012381    1
TXN002701    1
TXN020591    1
TXN021012    1
TXN005713    1
TXN007854    1
TXN002537    1
TXN003928    1
TXN015423    1
TXN008813    1
TXN021917    1
TXN013045    1
TXN012350    1
TXN000252    1
TXN016044    1
TXN017886    1
TXN019154    1
TXN006840    1
TXN017410    1
TXN001655    1
TXN017108    1
TXN012202    1
TXN022845    1
TXN005854    1
TXN020619    1
TXN002956    1
TXN020788    1
TXN022949    1
TXN023597    1
TXN020804    1
TXN002949    1
TXN024011    1
TXN024507    1
TXN013766    1
TXN018570    1
TXN015196    1
TXN012223    1
TXN017364    1
TXN006216    1
TXN015348    1
TXN007572    1
TXN007528    1
TXN010647    1
TXN012528    1
TXN023501    1
TXN011155    1
TXN010284    1
TXN017817    1
TXN024213    1
TXN014492    1
TXN023000    1
TXN002104    1
TXN017200    1
TXN006541    1
TXN007242    1
TXN018652    1
TXN011103    1
TXN024715    1
TXN004814    1
TXN021722    1
TXN005418    1
TXN017237    1
TXN002480    1
TXN012017    1
TXN001952    1
TXN009504    1
TXN004821    1
TXN012961    1
TXN003836    1
TXN014026    1
TXN019408    1
TXN014004    1
TXN023753    1
TXN014772    1
TXN010915    1
TXN012925    1
TXN016111    1
TXN023191    1
TXN005746    1
TXN015822    1
TXN014430    1
TXN020338    1
TXN009404    1
TXN021821    1
TXN018189    1
TXN017616    1
TXN016121    1
TXN006745    1
TXN019122    1
TXN013854    1
TXN013091    1
TXN023163    1
TXN008066    1
TXN008052    1
TXN002772    1
TXN001585    1
TXN021295    1
TXN000976    1
TXN010651    1
TXN024630    1
TXN021688    1
TXN021836    1
TXN014620    1
TXN015117    1
TXN009662    1
TXN024819    1
TXN017229    1
TXN005155    1
TXN015287    1
TXN001072    1
TXN004503    1
TXN000394    1
TXN010723    1
TXN022490    1
TXN000163    1
TXN014954    1
TXN004349    1
TXN004192    1
TXN020881    1
TXN024984    1
TXN010696    1
TXN007617    1
TXN002705    1
TXN010450    1
TXN018991    1
TXN012306    1
TXN007989    1
TXN012366    1
TXN001367    1
TXN022599    1
TXN010520    1
TXN021888    1
TXN019077    1
TXN016457    1
TXN023168    1
TXN012723    1
TXN014600    1
TXN007452    1
TXN012834    1
TXN021612    1
TXN020542    1
TXN015869    1
TXN009569    1
TXN013184    1
TXN009899    1
TXN015415    1
TXN016183    1
TXN024104    1
TXN022939    1
TXN013221    1
TXN018559    1
TXN002946    1
TXN002036    1
TXN020449    1
TXN013053    1
TXN010758    1
TXN006890    1
TXN013094    1
TXN002084    1
TXN023757    1
TXN003507    1
TXN012504    1
TXN005210    1
TXN016155    1
TXN023364    1
TXN017216    1
TXN013686    1
TXN002220    1
TXN004990    1
TXN001901    1
TXN023400    1
TXN018358    1
TXN013627    1
TXN010663    1
TXN018006    1
TXN015929    1
TXN007970    1
TXN002044    1
TXN019372    1
TXN013021    1
TXN021465    1
TXN003125    1
TXN006325    1
TXN014955    1
TXN019019    1
TXN001377    1
TXN020493    1
TXN000106    1
TXN020215    1
TXN006486    1
TXN022359    1
TXN015896    1
TXN018974    1
TXN018360    1
TXN017451    1
TXN018233    1
TXN017996    1
TXN011510    1
TXN012470    1
TXN000691    1
TXN005316    1
TXN024969    1
TXN015735    1
TXN022145    1
TXN004248    1
TXN023560    1
TXN017809    1
TXN006162    1
TXN024072    1
TXN000594    1
TXN001080    1
TXN022157    1
TXN002119    1
TXN003888    1
TXN004478    1
TXN023023    1
TXN017039    1
TXN011122    1
TXN023794    1
TXN007249    1
TXN011546    1
TXN001674    1
TXN017786    1
TXN005616    1
TXN003996    1
TXN004977    1
TXN006213    1
TXN001285    1
TXN018798    1
TXN005648    1
TXN009286    1
TXN018247    1
TXN018516    1
TXN002276    1
TXN014918    1
TXN008159    1
TXN022309    1
TXN007361    1
TXN024631    1
TXN017066    1
TXN006366    1
TXN009361    1
TXN003329    1
TXN020131    1
TXN004449    1
TXN010556    1
TXN009423    1
TXN009784    1
TXN003574    1
TXN009824    1
TXN022029    1
TXN002382    1
TXN009435    1
TXN017909    1
TXN005026    1
TXN022376    1
TXN005736    1
TXN024634    1
TXN020655    1
TXN023433    1
TXN007494    1
TXN024977    1
TXN009084    1
TXN019600    1
TXN017044    1
TXN018695    1
TXN000258    1
TXN009933    1
TXN013270    1
TXN022122    1
TXN007413    1
TXN017152    1
TXN018575    1
TXN024299    1
TXN021331    1
TXN011056    1
TXN012707    1
TXN006218    1
TXN011503    1
TXN011364    1
TXN008490    1
TXN012812    1
TXN002918    1
TXN023279    1
TXN000806    1
TXN010256    1
TXN007654    1
TXN004688    1
TXN015474    1
TXN003712    1
TXN003031    1
TXN010431    1
TXN014525    1
TXN014754    1
TXN004697    1
TXN011250    1
TXN016384    1
TXN014653    1
TXN013235    1
TXN001579    1
TXN021631    1
TXN022363    1
TXN001974    1
TXN002567    1
TXN006523    1
TXN009041    1
TXN015486    1
TXN024175    1
TXN014581    1
TXN024435    1
TXN013770    1
TXN000242    1
TXN008470    1
TXN018906    1
TXN010016    1
TXN016369    1
TXN001980    1
TXN006985    1
TXN009349    1
TXN000002    1
TXN015136    1
TXN003832    1
TXN014837    1
TXN014083    1
TXN003615    1
TXN009292    1
TXN011322    1
TXN014366    1
TXN003542    1
TXN003231    1
TXN021809    1
TXN017059    1
TXN004273    1
TXN022915    1
TXN015378    1
TXN016909    1
TXN001308    1
TXN020305    1
TXN020980    1
TXN006187    1
TXN020553    1
TXN008336    1
TXN006718    1
TXN021787    1
TXN019847    1
TXN005459    1
TXN007343    1
TXN006716    1
TXN024275    1
TXN003688    1
TXN011907    1
TXN010137    1
TXN003519    1
TXN021442    1
TXN001735    1
TXN014138    1
TXN019791    1
TXN020738    1
TXN013976    1
TXN004035    1
TXN004532    1
TXN015528    1
TXN020822    1
TXN023201    1
TXN005361    1
TXN019044    1
TXN011739    1
TXN019899    1
TXN005695    1
TXN014788    1
TXN000978    1
TXN018724    1
TXN002596    1
TXN019760    1
TXN020323    1
TXN024096    1
TXN017178    1
TXN008047    1
TXN006362    1
TXN017672    1
TXN011903    1
TXN011463    1
TXN002396    1
TXN002530    1
TXN018736    1
TXN001392    1
TXN014218    1
TXN002679    1
TXN013437    1
TXN020213    1
TXN020704    1
TXN023669    1
TXN003132    1
TXN009475    1
TXN014479    1
TXN018016    1
TXN021370    1
TXN013336    1
TXN006507    1
TXN002402    1
TXN005922    1
TXN009469    1
TXN004628    1
TXN002965    1
TXN016933    1
TXN021200    1
TXN007215    1
TXN015667    1
TXN010806    1
TXN010272    1
TXN005844    1
TXN010737    1
TXN021661    1
TXN018070    1
TXN004004    1
TXN021474    1
TXN021046    1
TXN017292    1
TXN021937    1
TXN006378    1
TXN004708    1
TXN019902    1
TXN012051    1
TXN013618    1
TXN001554    1
TXN005549    1
TXN001487    1
TXN023968    1
TXN000847    1
TXN022379    1
TXN020856    1
TXN016338    1
TXN009093    1
TXN015113    1
TXN002582    1
TXN008295    1
TXN002451    1
TXN024405    1
TXN002308    1
TXN001389    1
TXN020721    1
TXN002230    1
TXN012889    1
TXN024778    1
TXN000211    1
TXN021487    1
TXN009947    1
TXN020319    1
TXN006666    1
TXN016521    1
TXN000411    1
TXN010116    1
TXN001760    1
TXN014189    1
TXN008255    1
TXN003025    1
TXN023469    1
TXN011456    1
TXN002678    1
TXN010017    1
TXN012073    1
TXN015192    1
TXN020933    1
TXN002788    1
TXN014055    1
TXN013059    1
TXN009955    1
TXN001162    1
TXN013218    1
TXN015751    1
TXN010548    1
TXN011972    1
TXN014209    1
TXN020261    1
TXN021340    1
TXN016771    1
TXN012895    1
TXN015817    1
TXN009986    1
TXN002758    1
TXN009328    1
TXN020041    1
TXN001803    1
TXN011267    1
TXN005570    1
TXN008726    1
TXN016690    1
TXN012002    1
TXN018327    1
TXN017670    1
TXN014051    1
TXN015786    1
TXN013357    1
TXN004880    1
TXN011445    1
TXN003255    1
TXN011009    1
TXN011033    1
TXN010518    1
TXN004760    1
TXN014276    1
TXN005374    1
TXN010863    1
TXN017918    1
TXN021274    1
TXN018894    1
TXN022833    1
TXN001302    1
TXN014198    1
TXN013742    1
TXN012640    1
TXN014693    1
TXN023282    1
TXN011743    1
TXN012830    1
TXN014942    1
TXN011589    1
TXN005327    1
TXN017874    1
TXN021472    1
TXN005678    1
TXN009459    1
TXN023391    1
TXN022947    1
TXN024846    1
TXN010304    1
TXN009966    1
TXN001614    1
TXN011623    1
TXN017114    1
TXN009921    1
TXN012769    1
TXN000192    1
TXN015586    1
TXN020712    1
TXN017176    1
TXN011402    1
TXN016974    1
TXN010252    1
TXN011026    1
TXN008076    1
TXN014989    1
TXN007600    1
TXN010620    1
TXN023132    1
TXN014930    1
TXN001532    1
TXN001234    1
TXN007813    1
TXN017041    1
TXN007501    1
TXN015729    1
TXN017744    1
TXN017047    1
TXN017058    1
TXN022858    1
TXN019579    1
TXN005304    1
TXN004217    1
TXN011801    1
TXN012508    1
TXN006462    1
TXN012287    1
TXN007719    1
TXN015670    1
TXN019313    1
TXN018329    1
TXN018195    1
TXN018916    1
TXN006640    1
TXN003925    1
TXN021986    1
TXN014053    1
TXN022004    1
TXN016950    1
TXN014831    1
TXN004924    1
TXN008581    1
TXN003697    1
TXN014335    1
TXN006749    1
TXN015708    1
TXN006022    1
TXN014180    1
TXN004290    1
TXN002972    1
TXN014913    1
TXN017562    1
TXN019367    1
TXN010179    1
TXN012364    1
TXN010086    1
TXN007735    1
TXN015119    1
TXN016678    1
TXN015539    1
TXN016655    1
TXN013796    1
TXN015327    1
TXN003603    1
TXN001169    1
TXN010709    1
TXN022289    1
TXN012062    1
TXN014870    1
TXN011756    1
TXN021770    1
TXN002495    1
TXN003709    1
TXN002333    1
TXN016007    1
TXN008503    1
TXN023572    1
TXN019990    1
TXN008354    1
TXN019550    1
TXN002612    1
TXN012822    1
TXN003727    1
TXN010167    1
TXN006592    1
TXN010851    1
TXN017947    1
TXN013223    1
TXN017198    1
TXN023619    1
TXN006040    1
TXN013373    1
TXN007730    1
TXN003685    1
TXN006136    1
TXN021804    1
TXN014731    1
TXN012398    1
TXN022109    1
TXN000913    1
TXN004131    1
TXN010525    1
TXN014699    1
TXN017604    1
TXN017007    1
TXN020298    1
TXN002274    1
TXN001228    1
TXN024771    1
TXN001272    1
TXN004649    1
TXN008144    1
TXN004082    1
TXN023036    1
TXN000096    1
TXN007477    1
TXN019426    1
TXN009126    1
TXN003334    1
TXN000015    1
TXN017060    1
TXN019428    1
TXN006036    1
TXN013219    1
TXN007562    1
TXN013176    1
TXN023620    1
TXN019609    1
TXN017389    1
TXN006380    1
TXN000188    1
TXN014829    1
TXN010537    1
TXN007135    1
TXN020907    1
TXN020892    1
TXN010670    1
TXN011158    1
TXN010193    1
TXN013240    1
TXN007268    1
TXN018313    1
TXN003497    1
TXN001815    1
TXN000018    1
TXN017623    1
TXN023965    1
TXN002809    1
TXN023228    1
TXN002890    1
TXN009155    1
TXN024186    1
TXN020894    1
TXN022028    1
TXN003852    1
TXN013532    1
TXN010229    1
TXN001495    1
TXN000550    1
TXN000981    1
TXN023767    1
TXN005146    1
TXN008995    1
TXN014640    1
TXN001818    1
TXN009631    1
TXN013868    1
TXN007872    1
TXN023974    1
TXN018879    1
TXN008855    1
TXN014469    1
TXN010476    1
TXN016556    1
TXN003444    1
TXN003590    1
TXN014748    1
TXN019033    1
TXN006286    1
TXN009866    1
TXN009706    1
TXN004130    1
TXN020365    1
TXN014526    1
TXN010499    1
TXN014903    1
TXN002657    1
TXN016845    1
TXN000003    1
TXN013327    1
TXN002371    1
TXN012405    1
TXN024468    1
TXN010022    1
TXN007517    1
TXN000378    1
TXN016531    1
TXN023062    1
TXN020754    1
TXN002234    1
TXN003287    1
TXN005913    1
TXN002432    1
TXN017257    1
TXN014331    1
TXN009500    1
TXN015155    1
TXN022050    1
TXN023934    1
TXN002143    1
TXN006717    1
TXN012421    1
TXN007293    1
TXN012188    1
TXN013784    1
TXN021566    1
TXN014096    1
TXN020042    1
TXN005480    1
TXN023738    1
TXN020714    1
TXN003754    1
TXN005531    1
TXN019121    1
TXN008322    1
TXN021272    1
TXN005937    1
TXN006906    1
TXN016305    1
TXN009396    1
TXN019071    1
TXN002563    1
TXN005077    1
TXN002920    1
TXN000026    1
TXN018514    1
TXN001550    1
TXN017642    1
TXN001659    1
TXN008222    1
TXN020975    1
TXN008917    1
TXN010712    1
TXN014834    1

In [4624]:
# تلخيص الاختلافات بناءً على جميع الأعمدة
differences = []  # يجب أن تحتوي على البيانات المكررة مع الاختلافات في الأعمدة

# تلخيص الفروقات في الأعمدة
column_diff_count = {col: 0 for col in sales_transactions.columns}  # العد لكل عمود

for transaction_id, group in sales_transactions.groupby('Transaction_ID'):
    # إذا كانت هناك أكثر من صف مع نفس Transaction_ID
    if len(group) > 1:
        diff_columns = {}
        for column in group.columns:
            if group[column].nunique() > 1:  # إذا كانت هناك اختلافات في العمود
                diff_columns[column] = group[column].unique()
                column_diff_count[column] += 1
        differences.append((transaction_id, diff_columns))

# تلخيص النتائج
print("\nSummary of Differences:")
for column, count in column_diff_count.items():
    print(f"Cases with different {column}: {count}")

Summary of Differences:
Cases with different Transaction_ID: 0
Cases with different Store_ID: 0
Cases with different Date: 0
Cases with different Product_Category: 0
Cases with different Units_Sold: 0
Cases with different Revenue: 375
Cases with different Discount_Percentage: 0
Cases with different Customer_ID: 0

In [4625]:
# تحديد الصفوف المكررة بناءً على Transaction_ID
duplicate_transactions = sales_transactions[sales_transactions.duplicated(subset='Transaction_ID', keep=False)]

# عرض قيم Revenue لكل Transaction_ID مكرر
revenue_values = duplicate_transactions.groupby('Transaction_ID')['Revenue'].unique()

# عرض قيم Revenue لكل Transaction_ID
print("Revenue Values for Duplicate Transaction_IDs:\n", revenue_values)

#اتضح انه اختلاف فقط في الايرادات والاختلاف عباره عن كسور وبسيط جدا فلذلك بناخذ العدد المقرب وليس اللي فيه كسور كثيره 
# حذف 375 صف من الملف 
#قررت اخذ اللي عنده قيمة الايرادات النظيف بدون كسور واللي له كسور كثيره يتم حذفه لان الرقم النظيف هو اقرب للفاتوره الصحيحه

Revenue Values for Duplicate Transaction_IDs:
 Transaction_ID
TXN000055    [3101.6627528600447, 3103.35]
TXN000098    [3322.71, 3332.4818213267663]
TXN000203     [171.32733298231742, 180.11]
TXN000204    [2277.9736530932573, 2280.57]
TXN000364      [319.5450492693837, 324.96]
TXN000416      [2393.1, 2402.756501891008]
TXN000444     [2205.22, 2209.356229607718]
TXN000574    [3339.67, 3337.7897662801506]
TXN000606    [2421.89, 2423.3357684359703]
TXN000653      [398.68, 398.8544601807936]
TXN000746      [4535.059110704508, 4527.1]
TXN000786    [4012.03, 4003.4434535858154]
TXN000834      [1230.04, 1233.16005215549]
TXN000859      [560.84, 568.3523054060678]
TXN000870    [2367.11, 2374.1308214873134]
TXN000874      [762.14, 762.4185634064594]
TXN000987     [2545.54, 2548.915424897569]
TXN001109      [734.4361586764275, 741.21]
TXN001115     [2736.552801148621, 2727.02]
TXN001117     [1626.56, 1618.581538814822]
TXN001173      [743.13, 742.8728949746045]
TXN001174    [2034.02, 2026.1932614168504]
TXN001186     [4204.170509394492, 4200.49]
TXN001330     [2669.36, 2661.748820420495]
TXN001335     [3570.032745099891, 3576.35]
TXN001375     [4331.59, 4335.684513909228]
TXN001446      [145.56714100767186, 137.2]
TXN001490      [930.6059701158146, 924.29]
TXN001527      [3977.10130203452, 3971.47]
TXN001893     [1003.05, 1004.122311266422]
TXN001910    [2826.7055083644536, 2825.25]
TXN002191    [2614.5403766536424, 2619.03]
TXN002236     [3633.099252950848, 3638.32]
TXN002257    [3710.6561021384655, 3702.72]
TXN002263     [1705.657231170007, 1703.69]
TXN002380     [131.36, 122.32353168973424]
TXN002387     [100.51, 101.88751529957266]
TXN002433    [2994.41, 2986.4542602633364]
TXN002468     [4108.487924583334, 4100.27]
TXN002541    [1521.6069758664316, 1522.77]
TXN002549     [1784.2869257763623, 1783.3]
TXN002830     [1948.1193304116891, 1948.4]
TXN003041    [1461.2300812854685, 1468.85]
TXN003171     [4848.84, 4847.135154284991]
TXN003207     [5002.575808585947, 4994.19]
TXN003457    [3052.9751424757237, 3053.96]
TXN003479      [3886.278264135835, 3888.7]
TXN003495    [2741.1552987991404, 2741.76]
TXN003667    [2436.34, 2438.5941142805955]
TXN003733    [2130.7229122008425, 2128.93]
TXN003740     [2102.7, 2097.2268071011654]
TXN003741     [3942.15, 3947.688312557673]
TXN003809     [4631.481545845345, 4627.87]
TXN003816    [3192.5756670921714, 3183.46]
TXN003853      [304.24, 300.3997403272105]
TXN003927       [370.330575525849, 370.45]
TXN003943      [1181.312118139355, 1189.4]
TXN003965     [3297.219405966531, 3291.54]
TXN003971    [2713.4681276383044, 2711.27]
TXN003992     [3059.228711947532, 3064.88]
TXN004042     [4111.324362803895, 4117.27]
TXN004092       [92.64496738276142, 86.73]
TXN004233    [3568.8386602289315, 3574.94]
TXN004269     [122.83426286981022, 131.79]
TXN004322      [886.5666982549609, 882.13]
TXN004354     [4738.356923801042, 4739.33]
TXN004397    [1711.3123781721035, 1707.63]
TXN004401    [1339.15, 1335.0480328994915]
TXN004411    [2046.38, 2049.7743876790337]
TXN004458     [3922.71, 3914.926671018826]
TXN004516     [4841.737954154199, 4848.82]
TXN004524     [2261.86, 2261.177080173539]
TXN004767      [376.93, 373.7502960139354]
TXN004849     [2565.52, 2570.718555540898]
TXN004881     [4530.248185699717, 4532.64]
TXN005025     [1752.72, 1743.934166640758]
TXN005142    [1407.0555825417557, 1401.13]
TXN005183     [212.99438302842657, 206.22]
TXN005269      [2473.8, 2467.853095795314]
TXN005347      [938.9368315540048, 941.68]
TXN005400      [3314.830428191707, 3304.9]
TXN005446     [4729.57, 4730.348901448568]
TXN005664       [82.26, 78.57474582588547]
TXN005741    [4239.6703174630975, 4248.96]
TXN005758      [2995.475637560669, 3004.3]
TXN005871     [2911.3, 2911.6875960932325]
TXN005918      [296.9723458902142, 287.66]
TXN005924    [2955.1097317719964, 2957.56]
TXN006018      [573.7796016133508, 579.65]
TXN006021     [4939.11, 4938.271070377457]
TXN006056      [861.8010953370607, 858.65]
TXN006215     [3728.23, 3721.493118992165]
TXN006224    [2760.66, 2757.3932762202207]
TXN006283    [1805.4217123202716, 1814.88]
TXN006326     [3430.54, 3427.400333729321]
TXN006336    [2841.51, 2844.1836203125667]
TXN006337     [2050.595027007958, 2051.41]
TXN006479    [2389.0187290934214, 2381.78]
TXN006510    [1014.23, 1020.0915429395974]
TXN006602    [2069.65, 2077.4698671196884]
TXN006609    [3187.73, 3189.0368670263765]
TXN006663     [2632.230095285874, 2640.07]
TXN006802     [4501.15, 4509.574341645146]
TXN006962    [1423.4423697789543, 1429.62]
TXN007043      [4250.5, 4250.163799254343]
TXN007045     [4621.811369312952, 4611.88]
TXN007116     [4889.700263584962, 4885.31]
TXN007143     [207.92038687821423, 202.37]
TXN007176    [1096.72, 1093.1400435250505]
TXN007204     [3377.75, 3382.031394194404]
TXN007231      [3412.70173460312, 3415.43]
TXN007263     [2728.2, 2729.1931448133764]
TXN007300    [2727.5834619184143, 2734.39]
TXN007309      [3806.91415451448, 3810.94]
TXN007321    [3970.82, 3970.2523001625286]
TXN007339     [1478.996635687669, 1469.36]
TXN007387     [1667.44, 1666.829830519412]
TXN007402     [4116.47, 4115.677821724678]
TXN007482     [4029.674779550962, 4037.31]
TXN007597     [234.65588905540028, 244.45]
TXN007604     [4871.19, 4873.765297924885]
TXN007677     [4409.82, 4413.142796667177]
TXN007716       [344.966209082883, 338.75]
TXN007748      [596.19, 601.5516771639127]
TXN007911    [1826.05, 1830.7669374152792]
TXN008150     [4326.16, 4329.334007913609]
TXN008176    [1220.8458316643914, 1230.01]
TXN008331      [1876.256186908587, 1869.7]
TXN008385    [2413.88, 2417.8369663187345]
TXN008409      [252.16, 243.8862296096791]
TXN008431    [1795.18, 1791.2784242838063]
TXN008461     [3375.301165089816, 3365.72]
TXN008481    [2411.1173903027607, 2403.51]
TXN008501     [2883.47, 2882.779314706152]
TXN008672      [272.6394654096498, 265.84]
TXN008673     [4524.425844924917, 4529.22]
TXN008771     [4581.62, 4576.500990506258]
TXN008802     [4393.55, 4384.662194016231]
TXN009071      [2166.73510871252, 2162.19]
TXN009087     [98062.15834158978, 4673.37]
TXN009387     [2875.34, 2884.019501540134]
TXN009388      [737.84, 736.3477301906817]
TXN009480      [781.36, 780.3389011625642]
TXN009521     [4574.548024190256, 4577.01]
TXN009591    [2760.31, 2752.6126795347377]
TXN009621      [4276.842840267317, 4281.6]
TXN009622      [3723.06, 3714.30533905086]
TXN009691     [1882.4318521583268, 1890.0]
TXN009740      [195.1299171622541, 200.49]
TXN009829     [4631.97, 4624.814390055991]
TXN009952     [3992.980638097858, 3997.01]
TXN009979    [2967.8586283999184, 2963.34]
TXN010001    [3018.22, 3023.1667861443048]
TXN010007    [1331.88, 1328.4653441816072]
TXN010136     [4503.153060452525, 4496.73]
TXN010254     [1026.4, 1021.2068483481808]
TXN010302    [2590.05, 2581.6676408589788]
TXN010393     [2935.889399881228, 2940.67]
TXN010460       [587.799780924606, 591.27]
TXN010480      [447.7211990871194, 439.91]
TXN010496     [3180.984830065449, 3173.69]
TXN010535     [2958.76, 2950.556650121781]
TXN010538    [3000.5563845097367, 3004.91]
TXN010545    [3113.7089442116817, 3114.02]
TXN010581    [4063.1183993781065, 4057.42]
TXN010599    [3691.26, 3691.8726851897486]
TXN010619     [2542.081972503489, 2534.01]
TXN010718     [364.35, 372.07479438405227]
TXN010789    [2842.4085429473776, 2848.73]
TXN010835     [1065.106528912583, 1057.09]
TXN010902    [1265.5286106436852, 1265.64]
TXN010982     [3984.262351294594, 3977.13]
TXN011038    [1114.0802288365414, 1122.31]
TXN011095      [731.8691553426919, 726.82]
TXN011238    [1128.0912563760087, 1137.77]
TXN011470      [886.7672984115823, 887.83]
TXN011504     [4567.498005428732, 4577.14]
TXN011543    [1165.8315655758493, 1169.72]
TXN011565      [772.75, 775.2135249902426]
TXN011675    [3501.95, 3504.9155433347705]
TXN011764    [2698.2535123328303, 2697.53]
TXN011837    [1210.6383088318894, 1213.22]
TXN011840    [1206.72, 1213.6229214905334]
TXN011852     [2980.06, 2983.879496420563]
TXN011855     [4966.279970466989, 4960.71]
TXN012088      [3770.5, 3773.224863701599]
TXN012125      [483.3202834257449, 478.77]
TXN012244    [1192.0093857490626, 1200.47]
TXN012293     [3047.442707598343, 3040.89]
TXN012389      [3607.94515417188, 3599.34]
TXN012516     [2027.435520108177, 2021.14]
TXN012627    [1777.27, 1769.2320178703992]
TXN012749     [4493.531587491932, 4500.66]
TXN012772      [406.9744322947184, 414.23]
TXN012940    [3380.6739888186225, 3387.23]
TXN012990     [2885.84, 2892.858159735287]
TXN013014    [3793.7500486375698, 3796.55]
TXN013233    [1959.1233241611512, 1955.21]
TXN013356     [3617.375175373465, 3620.95]
TXN013422     [304.59, 308.07851407379906]
TXN013452    [2348.3753725543597, 2341.14]
TXN013478     [3433.1258648577823, 3425.3]
TXN013517    [1345.15, 1336.5596715694444]
TXN013684      [2216.010578287007, 2208.5]
TXN013829     [4315.607339039322, 4309.58]
TXN013842      [2334.324037778096, 2339.8]
TXN013844     [3994.329983504987, 3994.62]
TXN013880      [541.9741193962349, 547.31]
TXN013995     [1307.240797432291, 1297.36]
TXN014031     [3862.212987090719, 3860.92]
TXN014048    [1496.11, 1501.0557039531614]
TXN014166     [4789.21, 4781.076938467776]
TXN014242     [3576.123287945765, 3575.86]
TXN014258    [2510.0576024939064, 2501.91]
TXN014337    [1269.61, 1271.4878930926648]
TXN014586     [3863.024269539867, 3861.36]
TXN014821      [3123.621182757479, 3114.7]
TXN014905       [83.37, 79.71236277399447]
TXN014969    [1630.0709075459874, 1622.22]
TXN015011     [1444.304448964924, 1438.28]
TXN015041    [1100.99, 1098.7146433547407]
TXN015138     [1705.34, 1708.986623978671]
TXN015152    [1372.4330831967193, 1371.46]
TXN015167     [4853.12, 4850.105405195369]
TXN015266     [3866.59, 3860.786048947551]
TXN015289      [866.5769105558909, 874.41]
TXN015297      [4757.689627207115, 4749.7]
TXN015332     [4985.428386425759, 4975.61]
TXN015338     [4826.99, 4832.326959241013]
TXN015451     [4945.296048610228, 4944.37]
TXN015615     [2228.89, 2225.192160341599]
TXN015621     [3295.22, 3297.548983250011]
TXN015648     [3366.6862863366164, 3365.0]
TXN015692     [4757.92, 4757.287717287548]
TXN015704     [3949.82, 3942.508589001184]
TXN015739     [2026.276046417996, 2029.66]
TXN015834     [1694.28, 1686.757223293231]
TXN015872        [497.1, 501.700480520844]
TXN015905     [303.14571302988134, 309.55]
TXN015908     [3358.69, 3368.206952032692]
TXN015942    [1854.47, 1850.2794283305689]
TXN016027      [1205.709700058528, 1203.2]
TXN016112    [4033.1832729880734, 4033.56]
TXN016124     [283.44600122284504, 276.55]
TXN016171    [2645.91, 2636.0361112672517]
TXN016175     [3330.36, 3328.746640298718]
TXN016294     [1670.121544853702, 1662.71]
TXN016387     [2179.325512153901, 2185.04]
TXN016393    [1220.77, 1222.8306256830683]
TXN016426    [3493.83, 3498.4628117683083]
TXN016474    [2807.67, 2808.4171129938736]
TXN016563    [1792.96, 1798.0366931017168]
TXN016629    [2914.47, 2908.9236222469567]
TXN016651       [948.306174165959, 948.13]
TXN016662     [1077.51, 1080.944880077851]
TXN016725     [3332.3, 3332.9690132893534]
TXN016762    [1272.6596227121722, 1266.75]
TXN016791     [4366.67, 4369.447799411915]
TXN016842     [167.18082061132515, 164.05]
TXN016975     [3637.91, 3637.025219430975]
TXN017006    [2145.1461772660814, 2147.21]
TXN017009      [595.5706053636588, 595.15]
TXN017078     [1653.76, 1653.695686551727]
TXN017169     [2594.72, 2587.026475799574]
TXN017240    [3159.54, 3167.0485341957883]
TXN017312    [1235.06, 1227.9346566774009]
TXN017384       [3480.13701641871, 3484.0]
TXN017498      [217.2843802922074, 223.16]
TXN017540       [265.4, 263.6227441735832]
TXN017566     [3888.595994672159, 3879.93]
TXN017648     [3428.18, 3429.351620546269]
TXN017844       [2959.45, 2950.8327723366]
TXN018083     [1339.4190796396124, 1334.2]
TXN018094     [4618.087270974962, 4615.76]
TXN018130    [3966.0635382779938, 3970.07]
TXN018159    [2162.6999968550344, 2159.52]
TXN018196     [2424.9719522388864, 2424.1]
TXN018197      [508.4309970997298, 506.38]
TXN018262     [4395.03, 4396.771027693452]
TXN018297     [3432.19, 3436.206814901299]
TXN018345    [2549.99, 2544.5005459606373]
TXN018356     [4021.199156855655, 4011.91]
TXN018396     [4705.78, 4713.522818220705]
TXN018422     [4066.58, 4074.081100406101]
TXN018432     [3704.955183380371, 3695.06]
TXN018442     [4390.667455956697, 4395.36]
TXN018460     [2523.44, 2518.593322849541]
TXN018649      [885.12, 891.1120859097772]
TXN018764      [655.1186054398726, 661.71]
TXN018814     [4193.431245854101, 4191.03]
TXN018881      [3860.0, 3863.608638119228]
TXN018893     [2826.13, 2831.756345619656]
TXN018932    [2957.0296660725235, 2959.45]
TXN019008     [4166.55, 4162.196868322159]
TXN019018      [712.31, 709.1373446871088]
TXN019049       [59.28087126701698, 60.99]
TXN019079      [530.8394260089965, 537.38]
TXN019090     [1222.6488779459107, 1231.1]
TXN019104     [4296.056701915724, 4286.88]
TXN019112     [3469.514590362202, 3468.52]
TXN019195     [3995.270006515773, 4005.01]
TXN019470    [2849.76, 2845.7431268062583]
TXN019492       [67.93180343568127, 64.89]
TXN019570     [3083.877406939641, 3076.94]
TXN019712     [3745.557337454164, 3743.64]
TXN019824     [4334.54, 4330.404516977704]
TXN019839    [1271.9507304561405, 1270.95]
TXN019979    [1755.64, 1758.9981655010247]
TXN020051    [2543.0304517415457, 2540.83]
TXN020071     [3574.78, 3566.889867885235]
TXN020172      [4667.9, 4663.823530016788]
TXN020415    [1590.51, 1599.0458350668964]
TXN020516    [1318.8995005218958, 1310.95]
TXN020659      [565.69, 568.0652629346885]
TXN020682    [2261.01, 2268.7093139951976]
TXN020951     [4292.877981182119, 4290.78]
TXN021011      [4312.235055841682, 4308.8]
TXN021035     [3479.081690726556, 3472.22]
TXN021036    [4897.85, 4904.9286002838535]
TXN021109     [4003.871920556616, 4001.78]
TXN021177     [2170.509505485769, 2172.82]
TXN021193       [609.48, 611.410852895114]
TXN021247     [426.28999190567737, 435.18]
TXN021358    [1147.04, 1139.0812962341902]
TXN021406     [3634.888647745408, 3627.48]
TXN021493     [3939.317699094633, 3935.66]
TXN021632     [4801.83, 4800.579196339218]
TXN021712     [2450.409537196172, 2446.34]
TXN021734     [1150.835278890327, 1150.52]
TXN021748      [1456.4, 1461.985310005566]
TXN021861     [3784.774219886168, 3778.04]
TXN021923     [1198.422691359574, 1194.28]
TXN021934     [4871.87, 4872.973303626374]
TXN022125    [3087.4784616010106, 3089.82]
TXN022150      [4305.0, 4299.406137381548]
TXN022338    [1217.74, 1221.7447187333898]
TXN022461    [4254.2597178960905, 4244.94]
TXN022565    [3259.68, 3267.1818173643637]
TXN022758    [3378.32, 3380.4637081099845]
TXN022819     [150.64, 142.86851068021463]
TXN022876    [1203.53, 1202.6025239958676]
TXN022886    [2657.31, 2648.9130681421807]
TXN022948      [302.8104594646725, 300.29]
TXN023026     [1319.1, 1327.7483622606849]
TXN023107    [1887.81, 1878.7710884215944]
TXN023174       [774.437914446698, 778.67]
TXN023241     [159.99403848210483, 164.85]
TXN023264     [1918.736849683744, 1927.45]
TXN023271    [4794.61, 4787.2426849872045]
TXN023302     [1031.7723289043065, 1022.4]
TXN023318      [953.9541476736512, 962.88]
TXN023358     [2949.058178101021, 2947.25]
TXN023526      [942.1587943560842, 943.13]
TXN023540    [3308.28, 3303.4289694806844]
TXN023549     [1610.6740952158898, 1601.2]
TXN023611     [4918.239179700591, 4926.99]
TXN023708     [4744.702245788395, 4748.81]
TXN023721     [2232.0, 2223.3092567589074]
TXN023832     [335.65, 341.04019726674335]
TXN023878    [2072.6295902859247, 2073.54]
TXN024027     [4816.14, 4812.882465870207]
TXN024066     [4144.08, 4148.248754260842]
TXN024168    [4600.5372235611785, 4592.58]
TXN024189     [3204.42, 3204.351614875185]
TXN024289      [495.59, 504.8575141539424]
TXN024609     [4408.95, 4415.055409127937]
TXN024683      [3115.46, 3117.27054622705]
TXN024685     [3627.39, 3621.835576618265]
TXN024721     [4580.427966464842, 4586.37]
TXN024727    [1512.1690730187847, 1506.12]
TXN024731    [1831.4954695045697, 1822.62]
TXN024808    [1362.98, 1366.6321414449326]
TXN024845    [2576.69, 2576.4753170457207]
TXN024921    [3354.88, 3351.5962623174883]
TXN024993     [3956.51, 3954.478107956704]
Name: Revenue, dtype: object

In [4626]:


# تحديد الصفوف المكررة بناءً على Transaction_ID
duplicate_transactions = sales_transactions[sales_transactions.duplicated(subset='Transaction_ID', keep=False)]

# تصفية الصفوف المكررة التي تحتوي على إيرادات بأرقام عشرية كثيرة (أكثر من منزلتين عشريتين)
rows_with_large_decimals = duplicate_transactions[duplicate_transactions['Revenue'].apply(lambda x: len(str(x).split('.')[-1]) > 2)]

# حذف الصفوف المكررة التي تحتوي على إيرادات بكسور كثيرة
sales_transactions= sales_transactions.drop(rows_with_large_decimals.index)



# عرض عدد الصفوف بعد الحذف للتأكد
print(sales_transactions.shape)

(25000, 8)

In [4627]:
sales_transactions.head()

,Transaction_ID,Store_ID,Date,Product_Category,Units_Sold,Revenue,Discount_Percentage,Customer_ID
0,TXN023368,STORE_027,2024-05-20,Electronics,9,"1,794",15,CUST00836
1,TXN004823,STORE_039,2023-04-19,Home & Garden,11,373,5,CUST06683
2,TXN024939,STORE_029,2023-03-04,Food & Beverage,4,"4,268",15,CUST03565
3,TXN015257,STORE_033,2024-06-03,Electronics,39,"4,325",0,CUST07318
4,TXN024609,STORE_021,2023-05-30,Electronics,42,"4,409",0,CUST07210

In [4628]:
# التحقق من وجود الصفوف المكررة بناءً على Transaction_ID بعد الحذف
duplicate_transaction_ids = sales_transactions[sales_transactions.duplicated(subset='Transaction_ID', keep=False)]

# عرض التكرارات المتبقية (إذا كانت موجودة)
print(f"عدد الصفوف المكررة المتبقية: {duplicate_transaction_ids.shape[0]}")

# عرض بعض الصفوف المكررة المتبقية
print("\nRows with Duplicate Transaction_IDs after cleaning:")
print(duplicate_transaction_ids.head())

عدد الصفوف المكررة المتبقية: 0

Rows with Duplicate Transaction_IDs after cleaning:
Empty DataFrame
Columns: [Transaction_ID, Store_ID, Date, Product_Category, Units_Sold, Revenue, Discount_Percentage, Customer_ID]
Index: []

In [4629]:
## نبدا في الملف الثاني

In [4630]:
# check the data shape
print(store_information.shape)

(46, 7)

In [4631]:
# استعراض صفوف

store_information.head(46)

,Store_ID,Region,City,Store_Size_SQM,Opening_Date,Staff_Count,Monthly_Rent
0,Store_001,Central,Riyadh,1107,30/7/2021,23,"115,878"
1,Store_002,Eastern,Jubail,350,27/3/2023,44,"34,482"
2,Store_003,Northern,Arar,609,30/7/2021,49,"39,420"
3,Store_004,Central,Qassim,496,6/7/2020,11,"56,494"
4,Store_005,Central,Qassim,1543,17/2/2023,9,"133,174"
5,Store_006,Western,Taif,1558,18/2/2022,24,NaN
6,Store_007,Western,Jeddah,1212,27/4/2020,17,"87,844"
7,Store_008,Western,Medina,554,4/8/2022,12,"131,482"
8,Store_009,Western,Medina,492,1/9/2021,36,"27,439"
9,Store_010,Northern,Arar,1562,30/9/2023,41,"37,524"
10,Store_011,Western,Makkah,844,24/11/2023,33,"124,644"
11,STORE-012,Central,Qassim,1683,18/8/2021,8,"124,028"
12,STORE-013,Central,Qassim,1941,23/10/2022,50,"94,892"
13,STORE-014,Eastern,Khobar,739,28/8/2020,22,"56,476"
14,STORE-015,Eastern,Dhahran,1078,22/9/2021,31,"161,147"
15,STORE-016,Northern,Tabuk,1436,12/9/2022,10,"126,671"
16,STORE-017,Southern,Abha,1921,3/7/2020,13,"115,958"
17,STORE-018,Central,Qassim,624,8/5/2021,27,"142,424"
18,STORE-019,Northern,Arar,1503,30/3/2023,44,"113,379"
19,STORE-020,Northern,Arar,1423,15/8/2022,25,"137,261"
20,STORE-021,Northern,Arar,929,7/5/2022,22,NaN
21,22,Northern,Arar,972,23/3/2022,33,"125,435"
22,23,Eastern,Dammam,650,11/9/2021,49,"99,935"
23,24,Central,Qassim,1396,24/7/2021,5,NaN
24,25,Western,Medina,1794,17/10/2020,15,"34,497"
25,26,Northern,Arar,1721,24/12/2021,17,"111,978"
26,STORE_027,Western,Medina,1677,10/8/2021,49,"103,190"
27,STORE_028,Western,Jeddah,827,28/3/2022,11,"21,729"
28,STORE_029,Central,Qassim,1371,18/11/2022,17,"61,338"
29,STORE_030,Southern,Abha,1913,18/4/2020,26,"130,465"
30,STORE_031,Southern,Abha,1765,19/6/2023,40,"45,152"
31,STORE_032,Northern,Arar,354,22/8/2021,30,"96,186"
32,STORE_033,Central,Qassim,1419,26/9/2023,10,"90,376"
33,STORE_034,Western,Taif,1045,24/12/2021,18,"101,191"
34,STORE_035,Northern,Tabuk,274,19/10/2021,34,"149,826"
35,STORE_036,Southern,Abha,1767,7/6/2021,10,"22,231"
36,STORE_037,Southern,Abha,1219,3/1/2022,7,"146,949"
37,STORE_038,Southern,Jizan,320,9/9/2023,18,"62,394"
38,STORE_039,Eastern,Dhahran,429,5/3/2021,32,"170,283"
39,STORE_040,Eastern,Dammam,457,1/12/2023,43,"157,157"
40,STORE_041,Eastern,Khobar,1691,1/11/2020,49,"146,301"
41,STORE_042,Central,Hail,1587,22/2/2023,26,"96,769"
42,STORE_043,Eastern,Dammam,591,23/7/2020,14,"142,392"
43,STORE_044,Central,Qassim,889,20/3/2023,27,NaN
44,STORE_045,Southern,Najran,954,14/3/2023,16,"139,670"
45,Store_006,Western,Duplicate_Error_City,1558,18/2/2022,24,"98,319"

In [4632]:

# عرض معلومات عن الأعمدة

store_information.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46 entries, 0 to 45
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Store_ID        46 non-null     object
 1   Region          46 non-null     object
 2   City            46 non-null     object
 3   Store_Size_SQM  46 non-null     int64
 4   Opening_Date    46 non-null     object
 5   Staff_Count     46 non-null     int64
 6   Monthly_Rent    42 non-null     float64
dtypes: float64(1), int64(2), object(4)
memory usage: 2.6+ KB

In [4633]:
# فحص القيم المفقودة في الأعمدة
print("\nMissing values in Store Information:")
store_information.isnull().sum()

Missing values in Store Information:

Store_ID          0
Region            0
City              0
Store_Size_SQM    0
Opening_Date      0
Staff_Count       0
Monthly_Rent      4
dtype: int64

In [4634]:


# عرض الإحصائيات الوصفية للبيانات الرقمية
print("\nDescriptive Statistics (Store Information):")
store_information.describe()

Descriptive Statistics (Store Information):

       Store_Size_SQM  Staff_Count  Monthly_Rent
count              46           46            42
mean            1,136           25       100,342
std               519           13        42,863
min               274            5        21,729
25%               630           14        61,602
50%             1,160           24       107,584
75%             1,561           34       132,751
max             1,941           50       170,283

In [4635]:
# حساب القيم الفريدة في City و Region
unique_cities = store_information['City'].unique()
unique_regions = store_information['Region'].unique()

# حساب عدد القيم الفريدة في Store_ID
unique_store_ids_count = store_information['Store_ID'].nunique()

# عرض النتائج
print(f"   City : {unique_cities}")


print(f"  Regions : {unique_regions}")


print(f"store_id : {unique_store_ids_count}")

   City : ['Riyadh' 'Jubail' 'Arar' 'Qassim' 'Taif' 'Jeddah' 'Medina' 'Makkah'
 'Khobar' 'Dhahran' 'Tabuk' 'Abha' 'Dammam' 'Jizan' 'Hail' 'Najran'
 'Duplicate_Error_City']
  Regions : ['Central' 'Eastern' 'Northern' 'Western' 'Southern']
store_id : 45

In [4636]:
# تعريف قائمة المدن والمناطق الصحيحة
city_region_map = {
    'Riyadh': 'Central', 
    'Jubail': 'Eastern', 
    'Arar': 'Northern', 
    'Qassim': 'Central', 
    'Taif': 'Western', 
    'Jeddah': 'Western', 
    'Medina': 'Western', 
    'Makkah': 'Western',
    'Khobar': 'Eastern', 
    'Dhahran': 'Eastern', 
    'Tabuk': 'Northern', 
    'Abha': 'Southern', 
    'Dammam': 'Eastern', 
    'Jizan': 'Southern', 
    'Hail': 'Central', 
    'Najran': 'Southern',
    
}

# التحقق من أن كل مدينة تتبع المنطقة الصحيحة
store_info_invalid_regions = store_information[store_information.apply(
    lambda row: city_region_map.get(row['City'], 'Unknown') != row['Region'], axis=1)]

# عرض الصفوف التي تحتوي على تباس بين المدينة والمنطقة
print(f"Number of rows with mismatched city-region: {store_info_invalid_regions.shape[0]}")
print(store_info_invalid_regions[['Store_ID', 'City', 'Region']].head(10))

Number of rows with mismatched city-region: 1
     Store_ID                  City   Region
45  Store_006  Duplicate_Error_City  Western

In [4637]:
# التحقق من وجود مسافات فارغة فقط في الأعمدة النصية
whitespace_rows = store_information[store_information.select_dtypes(include=['object']).apply(lambda x: x.str.contains('^\s*$', na=False)).any(axis=1)]

# عرض الصفوف التي تحتوي على مسافات فارغة في الأعمدة النصية
print("\nRows with White Spaces in Any Text Column:")
print(whitespace_rows)

Rows with White Spaces in Any Text Column:
Empty DataFrame
Columns: [Store_ID, Region, City, Store_Size_SQM, Opening_Date, Staff_Count, Monthly_Rent]
Index: []

In [4638]:
#عندي 4 قيم مفقوده في الايجار الشهري 
#كذلك تحويل نوع البيانات الى date  
#توحيد صيغة البيانات في عمود ال store id

In [4639]:
# تعديل دالة توحيد Store_ID
def standardize_store_id(store_id):
    # استخراج الرقم فقط من Store_ID
    store_id = re.sub(r'\D', '', str(store_id))  # إزالة أي حروف أو رموز غير رقمية
    return f"STORE_{store_id.zfill(3)}"  # توحيد التنسيق ليكون STORE_XXX

# تطبيق التوحيد على العمود Store_ID
store_information['Store_ID'] = store_information['Store_ID'].apply(standardize_store_id)

# التحقق من عدم وجود تكرار في Store_ID
duplicate_store_ids = store_information[store_information.duplicated(subset='Store_ID')]

# عرض Store_ID المكررة
print("Duplicate Store_IDs:\n", duplicate_store_ids)

Duplicate Store_IDs:
      Store_ID   Region                  City  Store_Size_SQM Opening_Date  \
45  STORE_006  Western  Duplicate_Error_City            1558    18/2/2022

    Staff_Count  Monthly_Rent
45           24        98,319

In [4640]:
# عرض أول 5 صفوف بعد توحيد Store_ID
print("\nStore Information (After Standardizing Store_ID):")
store_information.head(5)

Store Information (After Standardizing Store_ID):

,Store_ID,Region,City,Store_Size_SQM,Opening_Date,Staff_Count,Monthly_Rent
0,STORE_001,Central,Riyadh,1107,30/7/2021,23,"115,878"
1,STORE_002,Eastern,Jubail,350,27/3/2023,44,"34,482"
2,STORE_003,Northern,Arar,609,30/7/2021,49,"39,420"
3,STORE_004,Central,Qassim,496,6/7/2020,11,"56,494"
4,STORE_005,Central,Qassim,1543,17/2/2023,9,"133,174"

In [4641]:
#وجدنا قيمة الايجار  المفقوده في احد الصفوف المتكرره 
# تحديد الصفوف المكررة بناءً على Store_ID
duplicates = store_information[store_information.duplicated(subset='Store_ID', keep='first')]

# عرض الصفوف المكررة لتحديد المشكلة
print("Duplicate Store_IDs:")
print(duplicates)

# التعامل مع الصفوف المكررة:
# سنملأ NaN في Monthly_Rent من الصف الآخر الذي يحتوي على القيمة الصحيحة
store_information['Monthly_Rent'] = store_information.groupby('Store_ID')['Monthly_Rent'].transform(lambda x: x.fillna(method='bfill').fillna(method='ffill'))

# حذف الصف المكرر (الذي أخذنا منه القيمة)
store_information = store_information.drop(duplicates.index)

Duplicate Store_IDs:
     Store_ID   Region                  City  Store_Size_SQM Opening_Date  \
45  STORE_006  Western  Duplicate_Error_City            1558    18/2/2022

    Staff_Count  Monthly_Rent
45           24        98,319

In [4642]:
# تحويل العمود Date إلى نوع datetime مع توحيد الصيغ في DataFrame الصحيح
store_information['Opening_Date'] = pd.to_datetime(store_information['Opening_Date'], errors='coerce')

C:\Users\POWER\AppData\Local\Temp\ipykernel_35936\358555093.py:2: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  store_information['Opening_Date'] = pd.to_datetime(store_information['Opening_Date'], errors='coerce')

In [4643]:

# عرض أقدم وأحدث تاريخ
earliest_date = store_information['Opening_Date'].min()
latest_date = store_information['Opening_Date'].max()

print(f"\nEarliest Date in the data: {earliest_date}")
print(f"Latest Date in the data: {latest_date}")

Earliest Date in the data: 2020-01-11 00:00:00
Latest Date in the data: 2023-11-24 00:00:00

In [4644]:
store_information.head(46)

,Store_ID,Region,City,Store_Size_SQM,Opening_Date,Staff_Count,Monthly_Rent
0,STORE_001,Central,Riyadh,1107,2021-07-30,23,"115,878"
1,STORE_002,Eastern,Jubail,350,2023-03-27,44,"34,482"
2,STORE_003,Northern,Arar,609,2021-07-30,49,"39,420"
3,STORE_004,Central,Qassim,496,2020-06-07,11,"56,494"
4,STORE_005,Central,Qassim,1543,2023-02-17,9,"133,174"
5,STORE_006,Western,Taif,1558,2022-02-18,24,"98,319"
6,STORE_007,Western,Jeddah,1212,2020-04-27,17,"87,844"
7,STORE_008,Western,Medina,554,2022-04-08,12,"131,482"
8,STORE_009,Western,Medina,492,2021-01-09,36,"27,439"
9,STORE_010,Northern,Arar,1562,2023-09-30,41,"37,524"
10,STORE_011,Western,Makkah,844,2023-11-24,33,"124,644"
11,STORE_012,Central,Qassim,1683,2021-08-18,8,"124,028"
12,STORE_013,Central,Qassim,1941,2022-10-23,50,"94,892"
13,STORE_014,Eastern,Khobar,739,2020-08-28,22,"56,476"
14,STORE_015,Eastern,Dhahran,1078,2021-09-22,31,"161,147"
15,STORE_016,Northern,Tabuk,1436,2022-12-09,10,"126,671"
16,STORE_017,Southern,Abha,1921,2020-03-07,13,"115,958"
17,STORE_018,Central,Qassim,624,2021-08-05,27,"142,424"
18,STORE_019,Northern,Arar,1503,2023-03-30,44,"113,379"
19,STORE_020,Northern,Arar,1423,2022-08-15,25,"137,261"
20,STORE_021,Northern,Arar,929,2022-07-05,22,NaN
21,STORE_022,Northern,Arar,972,2022-03-23,33,"125,435"
22,STORE_023,Eastern,Dammam,650,2021-11-09,49,"99,935"
23,STORE_024,Central,Qassim,1396,2021-07-24,5,NaN
24,STORE_025,Western,Medina,1794,2020-10-17,15,"34,497"
25,STORE_026,Northern,Arar,1721,2021-12-24,17,"111,978"
26,STORE_027,Western,Medina,1677,2021-10-08,49,"103,190"
27,STORE_028,Western,Jeddah,827,2022-03-28,11,"21,729"
28,STORE_029,Central,Qassim,1371,2022-11-18,17,"61,338"
29,STORE_030,Southern,Abha,1913,2020-04-18,26,"130,465"
30,STORE_031,Southern,Abha,1765,2023-06-19,40,"45,152"
31,STORE_032,Northern,Arar,354,2021-08-22,30,"96,186"
32,STORE_033,Central,Qassim,1419,2023-09-26,10,"90,376"
33,STORE_034,Western,Taif,1045,2021-12-24,18,"101,191"
34,STORE_035,Northern,Tabuk,274,2021-10-19,34,"149,826"
35,STORE_036,Southern,Abha,1767,2021-07-06,10,"22,231"
36,STORE_037,Southern,Abha,1219,2022-03-01,7,"146,949"
37,STORE_038,Southern,Jizan,320,2023-09-09,18,"62,394"
38,STORE_039,Eastern,Dhahran,429,2021-05-03,32,"170,283"
39,STORE_040,Eastern,Dammam,457,2023-01-12,43,"157,157"
40,STORE_041,Eastern,Khobar,1691,2020-01-11,49,"146,301"
41,STORE_042,Central,Hail,1587,2023-02-22,26,"96,769"
42,STORE_043,Eastern,Dammam,591,2020-07-23,14,"142,392"
43,STORE_044,Central,Qassim,889,2023-03-20,27,NaN
44,STORE_045,Southern,Najran,954,2023-03-14,16,"139,670"

In [4645]:
# حساب متوسط الإيجار لكل مدينة
city_mean_rent = store_information.groupby('City')['Monthly_Rent'].mean()

# ملء القيم المفقودة في Monthly_Rent باستخدام المتوسط الخاص بكل مدينة
def fill_rent(row):
    if pd.isna(row['Monthly_Rent']):
        return city_mean_rent[row['City']]
    else:
        return row['Monthly_Rent']

# تطبيق التعديل على العمود Monthly_Rent
store_information['Monthly_Rent'] = store_information.apply(fill_rent, axis=1).round(2)

In [4646]:
store_information.head(45)

,Store_ID,Region,City,Store_Size_SQM,Opening_Date,Staff_Count,Monthly_Rent
0,STORE_001,Central,Riyadh,1107,2021-07-30,23,"115,878"
1,STORE_002,Eastern,Jubail,350,2023-03-27,44,"34,482"
2,STORE_003,Northern,Arar,609,2021-07-30,49,"39,420"
3,STORE_004,Central,Qassim,496,2020-06-07,11,"56,494"
4,STORE_005,Central,Qassim,1543,2023-02-17,9,"133,174"
5,STORE_006,Western,Taif,1558,2022-02-18,24,"98,319"
6,STORE_007,Western,Jeddah,1212,2020-04-27,17,"87,844"
7,STORE_008,Western,Medina,554,2022-04-08,12,"131,482"
8,STORE_009,Western,Medina,492,2021-01-09,36,"27,439"
9,STORE_010,Northern,Arar,1562,2023-09-30,41,"37,524"
10,STORE_011,Western,Makkah,844,2023-11-24,33,"124,644"
11,STORE_012,Central,Qassim,1683,2021-08-18,8,"124,028"
12,STORE_013,Central,Qassim,1941,2022-10-23,50,"94,892"
13,STORE_014,Eastern,Khobar,739,2020-08-28,22,"56,476"
14,STORE_015,Eastern,Dhahran,1078,2021-09-22,31,"161,147"
15,STORE_016,Northern,Tabuk,1436,2022-12-09,10,"126,671"
16,STORE_017,Southern,Abha,1921,2020-03-07,13,"115,958"
17,STORE_018,Central,Qassim,624,2021-08-05,27,"142,424"
18,STORE_019,Northern,Arar,1503,2023-03-30,44,"113,379"
19,STORE_020,Northern,Arar,1423,2022-08-15,25,"137,261"
20,STORE_021,Northern,Arar,929,2022-07-05,22,"94,455"
21,STORE_022,Northern,Arar,972,2022-03-23,33,"125,435"
22,STORE_023,Eastern,Dammam,650,2021-11-09,49,"99,935"
23,STORE_024,Central,Qassim,1396,2021-07-24,5,"100,389"
24,STORE_025,Western,Medina,1794,2020-10-17,15,"34,497"
25,STORE_026,Northern,Arar,1721,2021-12-24,17,"111,978"
26,STORE_027,Western,Medina,1677,2021-10-08,49,"103,190"
27,STORE_028,Western,Jeddah,827,2022-03-28,11,"21,729"
28,STORE_029,Central,Qassim,1371,2022-11-18,17,"61,338"
29,STORE_030,Southern,Abha,1913,2020-04-18,26,"130,465"
30,STORE_031,Southern,Abha,1765,2023-06-19,40,"45,152"
31,STORE_032,Northern,Arar,354,2021-08-22,30,"96,186"
32,STORE_033,Central,Qassim,1419,2023-09-26,10,"90,376"
33,STORE_034,Western,Taif,1045,2021-12-24,18,"101,191"
34,STORE_035,Northern,Tabuk,274,2021-10-19,34,"149,826"
35,STORE_036,Southern,Abha,1767,2021-07-06,10,"22,231"
36,STORE_037,Southern,Abha,1219,2022-03-01,7,"146,949"
37,STORE_038,Southern,Jizan,320,2023-09-09,18,"62,394"
38,STORE_039,Eastern,Dhahran,429,2021-05-03,32,"170,283"
39,STORE_040,Eastern,Dammam,457,2023-01-12,43,"157,157"
40,STORE_041,Eastern,Khobar,1691,2020-01-11,49,"146,301"
41,STORE_042,Central,Hail,1587,2023-02-22,26,"96,769"
42,STORE_043,Eastern,Dammam,591,2020-07-23,14,"142,392"
43,STORE_044,Central,Qassim,889,2023-03-20,27,"100,389"
44,STORE_045,Southern,Najran,954,2023-03-14,16,"139,670"

In [4647]:
# حفظ النسخة المعدلة من Sales_Transactions
sales_transactions.to_csv('Cleaned_Sales_Transactions.csv', index=False)

# حفظ النسخة المعدلة من Store_Information
store_information.to_csv('Cleaned_Store_Information.csv', index=False)

In [4648]:
Cleaned_Store_Information = pd.read_csv('Cleaned_Store_Information.csv')
Cleaned_Sales_Transactions = pd.read_csv('Cleaned_Sales_Transactions.csv')

In [4649]:
Cleaned_Store_Information.shape

(45, 7)

In [4650]:
Cleaned_Sales_Transactions.shape

(25000, 8)

In [4651]:
# نبدا بالملف الثالث

In [4652]:
customer_data.shape

(8000, 7)

In [4653]:
customer_data.head()

,Customer_ID,Age,Gender,City,Registration_Date,Loyalty_Member,Total_Lifetime_Spend
0,CUST00001,31,M,Khobar,2022-10-24,Yes,"6,369"
1,CUST00002,63,F,Hail,2022-06-15,No,"48,421"
2,CUST00003,58,F,Jizan,2023-11-18,Yes,"32,933"
3,CUST00004,64,F,Jeddah,2023-03-01,Yes,"20,377"
4,CUST00005,47,F,Abha,2023-08-11,No,"46,611"

In [4654]:
customer_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Customer_ID           8000 non-null   object
 1   Age                   7600 non-null   float64
 2   Gender                7600 non-null   object
 3   City                  8000 non-null   object
 4   Registration_Date     8000 non-null   object
 5   Loyalty_Member        8000 non-null   object
 6   Total_Lifetime_Spend  8000 non-null   float64
dtypes: float64(2), object(5)
memory usage: 437.6+ KB

In [4655]:
customer_data.isnull().sum()

Customer_ID               0
Age                     400
Gender                  400
City                      0
Registration_Date         0
Loyalty_Member            0
Total_Lifetime_Spend      0
dtype: int64

In [4656]:
customer_data.describe()

        Age  Total_Lifetime_Spend
count 7,600                 8,000
mean     45                24,966
std      16                14,424
min      18                   102
25%      31                12,659
50%      45                25,083
75%      60                37,455
max      74                49,999

In [4657]:
# التحقق من وجود مسافات فارغة فقط في الأعمدة النصية
whitespace_rows = customer_data[customer_data.select_dtypes(include=['object']).apply(lambda x: x.str.contains('^\s*$', na=False)).any(axis=1)]

# عرض الصفوف التي تحتوي على مسافات فارغة في الأعمدة النصية
print("\nRows with White Spaces in Any Text Column:")
print(whitespace_rows)

Rows with White Spaces in Any Text Column:
Empty DataFrame
Columns: [Customer_ID, Age, Gender, City, Registration_Date, Loyalty_Member, Total_Lifetime_Spend]
Index: []

In [4658]:
# حساب القيم الفريدة في City و gender
unique_cities = customer_data['City'].unique()
unique_Gender = customer_data['Gender'].unique()
unique_Loyalty_Member=customer_data['Loyalty_Member'].unique()
unique_Customer_ID_count = customer_data['Customer_ID'].nunique()

# عرض النتائج
print(f"   City : {unique_cities}")


print(f"  Gender : {unique_Gender}")
print(f" Loyalty_Member :{unique_Loyalty_Member}")
print(f"Customer_ID : {unique_Customer_ID_count}")

   City : ['Khobar' 'Hail' 'Jizan' 'Jeddah' 'Abha' 'Arar' 'Jubail' 'Taif' 'Qassim'
 'Najran' 'Riyadh' 'Mecca' 'Dammam' 'Tabuk' 'Dhahran' 'Medina']
  Gender : ['M' 'F' nan]
 Loyalty_Member :['Yes' 'No']
Customer_ID : 8000

In [4659]:
# تحويل العمود Date إلى نوع datetime مع توحيد الصيغ في DataFrame الصحيح
customer_data['Registration_Date'] = pd.to_datetime(customer_data['Registration_Date'], errors='coerce')

In [4660]:

# عرض أقدم وأحدث تاريخ
earliest_date = customer_data['Registration_Date'].min()
latest_date = customer_data['Registration_Date'].max()

print(f"\nEarliest Date in the data: {earliest_date}")
print(f"Latest Date in the data: {latest_date}")

Earliest Date in the data: 2022-01-01 00:00:00
Latest Date in the data: 2024-07-15 00:00:00

In [4661]:
#الان عندي 400 قيمه مفقود في الgender و 400 قيمه مفقوده في الage
#العمر المفقود تم استبداله بالمتوسط لكل مدينه والجنس تم استبداله بغير معروف
# Replace missing values in Gender with "Unknown"
customer_data['Gender'].fillna('Unknown', inplace=True)

# Display the number of missing values after replacement
print(f"Number of missing values in Gender after replacement: {customer_data['Gender'].isnull().sum()}")
# Calculate the average age for each city
age_by_city = customer_data.groupby('City')['Age'].mean().round()


print(age_by_city)
# Replace missing values in Age with the average age of each city
customer_data['Age'] = customer_data.apply(
    lambda row: age_by_city[row['City']] if pd.isnull(row['Age']) else row['Age'], axis=1)

# Display the number of missing values in Age after replacement
print(f"Number of missing values in Age after replacement: {customer_data['Age'].isnull().sum()}")

Number of missing values in Gender after replacement: 0
City
Abha      45
Arar      46
Dammam    47
Dhahran   45
Hail      45
Jeddah    45
Jizan     45
Jubail    45
Khobar    46
Mecca     46
Medina    45
Najran    45
Qassim    45
Riyadh    47
Tabuk     45
Taif      46
Name: Age, dtype: float64
Number of missing values in Age after replacement: 0

In [4662]:
# تحويل العمود Age من float إلى int
customer_data['Age'] = customer_data['Age'].astype('Int64')  

# التحقق من التعديل
print(f"Data types after conversion:\n{customer_data.dtypes}")

Data types after conversion:
Customer_ID                     object
Age                              Int64
Gender                          object
City                            object
Registration_Date       datetime64[ns]
Loyalty_Member                  object
Total_Lifetime_Spend           float64
dtype: object

In [4663]:
customer_data.to_csv('Cleaned_customer_data.csv', index=False)

In [4664]:
customer_data.head()

,Customer_ID,Age,Gender,City,Registration_Date,Loyalty_Member,Total_Lifetime_Spend
0,CUST00001,31,M,Khobar,2022-10-24,Yes,"6,369"
1,CUST00002,63,F,Hail,2022-06-15,No,"48,421"
2,CUST00003,58,F,Jizan,2023-11-18,Yes,"32,933"
3,CUST00004,64,F,Jeddah,2023-03-01,Yes,"20,377"
4,CUST00005,47,F,Abha,2023-08-11,No,"46,611"

In [4665]:
#الملف الرابع

In [4666]:
marketing_campaigns.shape

(218, 6)

In [4667]:
marketing_campaigns.head()

  Campaign_ID   Store_ID    Month Campaign_Type Budget_SAR  Impressions
0     CMP0001  STORE_033  2023-01    Influencer  46000 SAR      6758300
1     CMP0002  STORE_002  2023-01    Influencer      26000     47762300
2     CMP0003  STORE_002  2023-01       Outdoor     40,000     30217100
3     CMP0004  STORE_045  2023-01       Outdoor      47000     38244400
4     CMP0005  STORE_018  2023-01    Influencer       8000     29342800

In [4668]:
marketing_campaigns.info()
#اكتشفت مشكله ان عمود الBudget_SAR فيه اختلاف في صياغة القيم كذلك نوعها سترنق وليس انتجر

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 218 entries, 0 to 217
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Campaign_ID    218 non-null    object
 1   Store_ID       218 non-null    object
 2   Month          218 non-null    object
 3   Campaign_Type  218 non-null    object
 4   Budget_SAR     218 non-null    object
 5   Impressions    218 non-null    int64
dtypes: int64(1), object(5)
memory usage: 10.3+ KB

In [4669]:
marketing_campaigns.isnull().sum()

Campaign_ID      0
Store_ID         0
Month            0
Campaign_Type    0
Budget_SAR       0
Impressions      0
dtype: int64

In [4670]:

marketing_campaigns.describe()

       Impressions
count          218
mean       941,252
std      4,982,861
min         10,082
25%        130,957
50%        257,210
75%        372,085
max     47,762,300

In [4671]:
#Campaign_Type حساب القيم الفريدة في  و Campaign_ID
unique_Campaign_Type = marketing_campaigns['Campaign_Type'].unique()
unique_Campaign_ID = marketing_campaigns['Campaign_ID'].nunique()
unique_Store_ID = marketing_campaigns['Store_ID'].nunique()

# عرض النتائج
print(f"  unique_Campaign_ID : {unique_Campaign_ID}")
print(f"  unique_Campaign_Type : {unique_Campaign_Type}")
print(f"  unique_Store_ID : {unique_Store_ID}")
##هنا نكتشف ان عندنا 46 متجر وفي الحقيقه يوجد فقط 45 متجر نتاكد من المتجر الزايد
# عرض القيم الفريدة في Store_ID

  unique_Campaign_ID : 218
  unique_Campaign_Type : ['Influencer' 'Outdoor' 'Radio' 'Email' 'TV' 'Social Media']
  unique_Store_ID : 46

In [4672]:
unique_store_ids = marketing_campaigns['Store_ID'].unique()
print(f"Unique Store_ID values: {unique_store_ids}")
#اكتشفت عندي store_999 وهو متجر ليس موجود او انه وهمي 
#نشوف كم مره تكرر
# عرض الصفوف التي تحتوي على Store_ID "STORE_999"
store_999_rows = marketing_campaigns[marketing_campaigns['Store_ID'] == 'STORE_999']

# عرض الصفوف
print(f"Rows with Store_ID 'STORE_999':\n{store_999_rows}")

Unique Store_ID values: ['STORE_033' 'STORE_002' 'STORE_045' 'STORE_018' 'STORE_030' 'STORE_014'
 'STORE_024' 'STORE_005' 'STORE_041' 'STORE_031' 'STORE_019' 'STORE_040'
 'STORE_029' 'STORE_027' 'STORE_003' 'STORE_007' 'STORE_015' 'STORE_013'
 'STORE_042' 'STORE_999' 'STORE_009' 'STORE_037' 'STORE_023' 'STORE_001'
 'STORE_011' 'STORE_010' 'STORE_020' 'STORE_043' 'STORE_008' 'STORE_006'
 'STORE_044' 'STORE_021' 'STORE_016' 'STORE_035' 'STORE_025' 'STORE_032'
 'STORE_012' 'STORE_036' 'STORE_004' 'STORE_034' 'STORE_038' 'STORE_022'
 'STORE_039' 'STORE_026' 'STORE_028' 'STORE_017']
Rows with Store_ID 'STORE_999':
    Campaign_ID   Store_ID    Month Campaign_Type Budget_SAR  Impressions
23      CMP0024  STORE_999  2023-02    Influencer      14000       486877
55      CMP0056  STORE_999  2023-05    Influencer        43K       296235
62      CMP0063  STORE_999  2023-06  Social Media  27000 SAR       406964
111     CMP0112  STORE_999  2023-10         Email      38000       240248
159     CMP0160  STORE_999  2024-02         Radio      38000        53272
167     CMP0168  STORE_999  2024-02    Influencer        19K       109644
170     CMP0171  STORE_999  2024-03         Radio       8000       373436
186     CMP0187  STORE_999  2024-04         Radio      27000       171839
188     CMP0189  STORE_999  2024-04    Influencer       7000       260985
198     CMP0199  STORE_999  2024-05         Radio      49000        30986

In [4673]:
# التحقق من وجود مسافات فارغة فقط في الأعمدة النصية
whitespace_rows = marketing_campaigns[marketing_campaigns.select_dtypes(include=['object']).apply(lambda x: x.str.contains('^\s*$', na=False)).any(axis=1)]

# عرض الصفوف التي تحتوي على مسافات فارغة في الأعمدة النصية
print("\nRows with White Spaces in Any Text Column:")
print(whitespace_rows)

Rows with White Spaces in Any Text Column:
Empty DataFrame
Columns: [Campaign_ID, Store_ID, Month, Campaign_Type, Budget_SAR, Impressions]
Index: []

In [4674]:
# تحويل عمود Month إلى نوع تاريخ (datetime)
marketing_campaigns['Month'] = pd.to_datetime(marketing_campaigns['Month'], format='%Y-%m')

# التحقق من نوع البيانات بعد التحويل
print(f"Data type of Month after conversion: {marketing_campaigns['Month'].dtype}")

Data type of Month after conversion: datetime64[ns]

In [4675]:
# حذف الصفوف التي تحتوي على Store_ID "STORE_999"
marketing_campaigns = marketing_campaigns[marketing_campaigns['Store_ID'] != 'STORE_999']

# عرض عدد الصفوف بعد الحذف
print(f" rows after delete  : {marketing_campaigns.shape[0]}")

 rows after delete  : 208

In [4676]:
# عرض أقدم وأحدث تاريخ
earliest_date = marketing_campaigns['Month'].min()
latest_date = marketing_campaigns['Month'].max()

print(f"\nEarliest Date in the data: {earliest_date}")
print(f"Latest Date in the data: {latest_date}")

Earliest Date in the data: 2023-01-01 00:00:00
Latest Date in the data: 2024-06-01 00:00:00

In [4677]:
# تنظيف عمود Budget_SAR
import re

def clean_budget(value):
    value = str(value).strip()
    value = value.upper().replace('SAR', '').replace(',', '').strip()
    if value.endswith('K'):
        return int(float(value[:-1]) * 1000)
    return int(float(value))

marketing_campaigns['Budget_SAR'] = marketing_campaigns['Budget_SAR'].apply(clean_budget)

print(marketing_campaigns[['Campaign_ID', 'Budget_SAR']].to_string())
print("\nنوع البيانات:", marketing_campaigns['Budget_SAR'].dtype)

    Campaign_ID  Budget_SAR
0       CMP0001       46000
1       CMP0002       26000
2       CMP0003       40000
3       CMP0004       47000
4       CMP0005        8000
5       CMP0006       10000
6       CMP0007       15000
7       CMP0008       30000
8       CMP0009       11000
9       CMP0010       18000
10      CMP0011       25000
11      CMP0012       18000
12      CMP0013       42000
13      CMP0014       47000
14      CMP0015       24000
15      CMP0016       22000
16      CMP0017       17000
17      CMP0018       12000
18      CMP0019       50000
19      CMP0020        5000
20      CMP0021       23000
21      CMP0022       11000
22      CMP0023       42000
24      CMP0025       29000
25      CMP0026       33000
26      CMP0027       31000
27      CMP0028       17000
28      CMP0029       25000
29      CMP0030       50000
30      CMP0031       24000
31      CMP0032       15000
32      CMP0033       20000
33      CMP0034       25000
34      CMP0035       11000
35      CMP0036        5000
36      CMP0037       12000
37      CMP0038       44000
38      CMP0039       45000
39      CMP0040       14000
40      CMP0041       10000
41      CMP0042        7000
42      CMP0043       49000
43      CMP0044       26000
44      CMP0045       28000
45      CMP0046       26000
46      CMP0047        8000
47      CMP0048       24000
48      CMP0049       46000
49      CMP0050       30000
50      CMP0051       10000
51      CMP0052       21000
52      CMP0053       35000
53      CMP0054       26000
54      CMP0055       43000
56      CMP0057       30000
57      CMP0058       29000
58      CMP0059       30000
59      CMP0060       49000
60      CMP0061       40000
61      CMP0062       27000
63      CMP0064       20000
64      CMP0065       45000
65      CMP0066       38000
66      CMP0067        6000
67      CMP0068       29000
68      CMP0069       46000
69      CMP0070        9000
70      CMP0071       13000
71      CMP0072       17000
72      CMP0073       46000
73      CMP0074       13000
74      CMP0075       46000
75      CMP0076       14000
76      CMP0077       38000
77      CMP0078       26000
78      CMP0079        5000
79      CMP0080       41000
80      CMP0081       14000
81      CMP0082       34000
82      CMP0083       30000
83      CMP0084       28000
84      CMP0085       15000
85      CMP0086       30000
86      CMP0087       44000
87      CMP0088       39000
88      CMP0089       41000
89      CMP0090       46000
90      CMP0091       50000
91      CMP0092       39000
92      CMP0093       31000
93      CMP0094        7000
94      CMP0095        9000
95      CMP0096       25000
96      CMP0097       15000
97      CMP0098       16000
98      CMP0099       29000
99      CMP0100       34000
100     CMP0101       29000
101     CMP0102       31000
102     CMP0103       10000
103     CMP0104       47000
104     CMP0105        8000
105     CMP0106       14000
106     CMP0107       46000
107     CMP0108       36000
108     CMP0109       22000
109     CMP0110       38000
110     CMP0111       38000
112     CMP0113       31000
113     CMP0114       35000
114     CMP0115       50000
115     CMP0116       32000
116     CMP0117       16000
117     CMP0118       44000
118     CMP0119       37000
119     CMP0120       38000
120     CMP0121       48000
121     CMP0122       38000
122     CMP0123       49000
123     CMP0124       12000
124     CMP0125       12000
125     CMP0126        9000
126     CMP0127       30000
127     CMP0128       16000
128     CMP0129       28000
129     CMP0130       26000
130     CMP0131       21000
131     CMP0132       43000
132     CMP0133        9000
133     CMP0134       43000
134     CMP0135       11000
135     CMP0136       11000
136     CMP0137       20000
137     CMP0138       37000
138     CMP0139       28000
139     CMP0140       19000
140     CMP0141        7000
141     CMP0142       43000
142     CMP0143       16000
143     CMP0144       32000
144     CMP0145       47000
145     CMP0146       35000
146     CMP0147       46000
147     CMP0148       24000
148     CMP0149       34000
149     CMP0150       29000
150     CMP0151       46000
151     CMP0152       35000
152     CMP0153       42000
153     CMP0154        8000
154     CMP0155       39000
155     CMP0156        5000
156     CMP0157        7000
157     CMP0158       50000
158     CMP0159       20000
160     CMP0161       32000
161     CMP0162       35000
162     CMP0163       23000
163     CMP0164       21000
164     CMP0165       20000
165     CMP0166        9000
166     CMP0167       33000
168     CMP0169       10000
169     CMP0170       37000
171     CMP0172       29000
172     CMP0173       35000
173     CMP0174       22000
174     CMP0175        6000
175     CMP0176       24000
176     CMP0177        7000
177     CMP0178        7000
178     CMP0179       38000
179     CMP0180        5000
180     CMP0181        8000
181     CMP0182       43000
182     CMP0183       39000
183     CMP0184        7000
184     CMP0185       15000
185     CMP0186       45000
187     CMP0188        7000
189     CMP0190       48000
190     CMP0191       46000
191     CMP0192       14000
192     CMP0193        9000
193     CMP0194       13000
194     CMP0195       21000
195     CMP0196       26000
196     CMP0197       28000
197     CMP0198       46000
199     CMP0200       26000
200     CMP0201       24000
201     CMP0202       31000
202     CMP0203       23000
203     CMP0204       37000
204     CMP0205       38000
205     CMP0206       35000
206     CMP0207       45000
207     CMP0208       19000
208     CMP0209       48000
209     CMP0210       15000
210     CMP0211       30000
211     CMP0212       21000
212     CMP0213       26000
213     CMP0214       45000
214     CMP0215        5000
215     CMP0216        6000
216     CMP0217       46000
217     CMP0218       42000

نوع البيانات: int64

In [4678]:
marketing_campaigns.to_csv('Cleaned_marketing_campaigns.csv', index=False)

In [4679]:
#الملف الخامس

In [4680]:
store_complaints.shape

(500, 6)

In [4681]:
store_complaints.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Complaint_ID    500 non-null    object
 1   Store_ID        50 non-null     object
 2   Date            50 non-null     object
 3   Complaint_Type  44 non-null     object
 4   Resolved        31 non-null     object
 5   Notes           0 non-null      float64
dtypes: float64(1), object(5)
memory usage: 23.6+ KB

In [4682]:
store_complaints.head()

  Complaint_ID Store_ID Date Complaint_Type Resolved  Notes
0     COMP0001      NaN  NaN            NaN      NaN    NaN
1     COMP0002      NaN  NaN            NaN      NaN    NaN
2     COMP0003      NaN  NaN            NaN      NaN    NaN
3     COMP0004      NaN  NaN            NaN      NaN    NaN
4     COMP0005      NaN  NaN            NaN      NaN    NaN

In [4683]:
store_complaints.isnull().sum()

Complaint_ID        0
Store_ID          450
Date              450
Complaint_Type    456
Resolved          469
Notes             500
dtype: int64

In [4684]:
# حساب القيم الفريدة    
unique_Complaint_Type = store_complaints['Complaint_Type'].unique()
unique_Resolved = store_complaints['Resolved'].unique()
unique_Complaint_ID = store_complaints['Complaint_ID'].nunique()
unique_Store_ID = store_complaints['Store_ID'].nunique()

# عرض النتائج
print(f"  unique_Complaint_Type : {unique_Complaint_Type}")
print(f"  unique_Resolved : {unique_Resolved}")
print(f"  unique_Complaint_ID : {unique_Complaint_ID}")
print(f"  unique_Store_ID : {unique_Store_ID}")

#الان نحذف جميع الصفوف ال450 التي ليس لها  store ID ويتبقى 50 صف نتعامل معه

  unique_Complaint_Type : [nan 'Other' 'Cleanliness' 'Product' 'Service']
  unique_Resolved : [nan 'Yes' 'No' 'Pending']
  unique_Complaint_ID : 500
  unique_Store_ID : 30

In [4685]:
# حذف الصفوف التي ليس لديها قيمة في عمود Store_ID
store_complaints = store_complaints.dropna(subset=['Store_ID'])

# عرض عدد الصفوف بعد الحذف
print(f"Number of rows after removing rows with missing Store_ID: {store_complaints.shape[0]}")
# حذف عمود Notes بالكامل
store_complaints = store_complaints.drop(columns=['Notes'])
# عرض بعض البيانات للتأكد
store_complaints.head(99)

Number of rows after removing rows with missing Store_ID: 50

    Complaint_ID   Store_ID        Date Complaint_Type Resolved
8       COMP0009  STORE_045  2023-07-13          Other      Yes
12      COMP0013  STORE_009  2023-04-27    Cleanliness      NaN
13      COMP0014  STORE_015  2023-12-10        Product       No
41      COMP0042  STORE_020  2024-06-22        Product       No
85      COMP0086  STORE_034  2024-01-11        Service      Yes
92      COMP0093  STORE_029  2023-01-20        Service      Yes
100     COMP0101  STORE_030  2024-06-26        Product      NaN
108     COMP0109  STORE_016  2023-02-08          Other      Yes
121     COMP0122  STORE_011  2023-02-01          Other      Yes
126     COMP0127  STORE_008  2023-05-15          Other      NaN
140     COMP0141  STORE_009  2024-02-22        Service       No
144     COMP0145  STORE_030  2023-08-11    Cleanliness  Pending
151     COMP0152  STORE_017  2023-10-24        Product       No
172     COMP0173  STORE_037  2023-12-18        Product       No
178     COMP0179  STORE_042  2023-07-02        Product      NaN
194     COMP0195  STORE_042  2023-12-03    Cleanliness      Yes
195     COMP0196  STORE_011  2024-04-23        Product      NaN
198     COMP0199  STORE_029  2024-03-05            NaN      NaN
209     COMP0210  STORE_024  2023-06-09            NaN       No
210     COMP0211  STORE_006  2024-05-27        Product  Pending
218     COMP0219  STORE_007  2024-01-22        Product       No
221     COMP0222  STORE_039  2024-02-09    Cleanliness      NaN
235     COMP0236  STORE_024  2023-03-23        Service  Pending
245     COMP0246  STORE_024  2023-09-20        Product       No
248     COMP0249  STORE_033  2023-01-24            NaN       No
255     COMP0256  STORE_036  2023-11-27        Service      NaN
281     COMP0282  STORE_023  2024-01-09        Product      NaN
287     COMP0288  STORE_040  2024-03-29        Service       No
305     COMP0306  STORE_017  2023-01-05            NaN      NaN
316     COMP0317  STORE_027  2023-05-04        Product      Yes
318     COMP0319  STORE_033  2024-01-15    Cleanliness  Pending
333     COMP0334  STORE_018  2023-09-28            NaN      NaN
339     COMP0340  STORE_029  2024-04-11        Service       No
349     COMP0350  STORE_013  2023-01-03        Service      NaN
352     COMP0353  STORE_015  2023-12-20    Cleanliness      NaN
359     COMP0360  STORE_004  2024-02-03        Service       No
362     COMP0363  STORE_024  2024-04-10    Cleanliness      NaN
365     COMP0366  STORE_044  2024-05-28        Service      NaN
370     COMP0371  STORE_028  2024-02-06        Service      NaN
380     COMP0381  STORE_011  2023-01-29          Other       No
384     COMP0385  STORE_031  2023-03-11          Other      Yes
412     COMP0413  STORE_044  2024-02-14          Other  Pending
425     COMP0426  STORE_017  2024-05-15        Product  Pending
436     COMP0437  STORE_030  2023-01-24        Product  Pending
453     COMP0454  STORE_009  2023-02-01    Cleanliness      NaN
454     COMP0455  STORE_036  2023-08-09        Product      Yes
466     COMP0467  STORE_044  2023-06-11          Other      Yes
469     COMP0470  STORE_005  2024-04-08    Cleanliness      NaN
489     COMP0490  STORE_027  2023-03-17            NaN      NaN
493     COMP0494  STORE_001  2023-07-18        Service      Yes

In [4686]:
store_complaints.shape

(50, 5)

In [4687]:
store_complaints.isnull().sum()

Complaint_ID       0
Store_ID           0
Date               0
Complaint_Type     6
Resolved          19
dtype: int64

In [4688]:
# تعبئة القيم الناقصة
store_complaints['Complaint_Type'] = store_complaints['Complaint_Type'].fillna('Other')
store_complaints['Resolved'] = store_complaints['Resolved'].fillna('Unknown')

# التحقق
print(store_complaints.isnull().sum())
print()
print(store_complaints[['Complaint_Type', 'Resolved']].value_counts())

Complaint_ID      0
Store_ID          0
Date              0
Complaint_Type    0
Resolved          0
dtype: int64

Complaint_Type  Resolved
Cleanliness     Unknown     6
Product         No          6
Other           Unknown     5
                Yes         5
Product         Unknown     4
Service         No          4
                Unknown     4
Other           No          3
Product         Pending     3
Service         Yes         3
Cleanliness     Pending     2
Product         Yes         2
Cleanliness     Yes         1
Other           Pending     1
Service         Pending     1
dtype: int64

In [4689]:
store_complaints.head(50)

    Complaint_ID   Store_ID        Date Complaint_Type Resolved
8       COMP0009  STORE_045  2023-07-13          Other      Yes
12      COMP0013  STORE_009  2023-04-27    Cleanliness  Unknown
13      COMP0014  STORE_015  2023-12-10        Product       No
41      COMP0042  STORE_020  2024-06-22        Product       No
85      COMP0086  STORE_034  2024-01-11        Service      Yes
92      COMP0093  STORE_029  2023-01-20        Service      Yes
100     COMP0101  STORE_030  2024-06-26        Product  Unknown
108     COMP0109  STORE_016  2023-02-08          Other      Yes
121     COMP0122  STORE_011  2023-02-01          Other      Yes
126     COMP0127  STORE_008  2023-05-15          Other  Unknown
140     COMP0141  STORE_009  2024-02-22        Service       No
144     COMP0145  STORE_030  2023-08-11    Cleanliness  Pending
151     COMP0152  STORE_017  2023-10-24        Product       No
172     COMP0173  STORE_037  2023-12-18        Product       No
178     COMP0179  STORE_042  2023-07-02        Product  Unknown
194     COMP0195  STORE_042  2023-12-03    Cleanliness      Yes
195     COMP0196  STORE_011  2024-04-23        Product  Unknown
198     COMP0199  STORE_029  2024-03-05          Other  Unknown
209     COMP0210  STORE_024  2023-06-09          Other       No
210     COMP0211  STORE_006  2024-05-27        Product  Pending
218     COMP0219  STORE_007  2024-01-22        Product       No
221     COMP0222  STORE_039  2024-02-09    Cleanliness  Unknown
235     COMP0236  STORE_024  2023-03-23        Service  Pending
245     COMP0246  STORE_024  2023-09-20        Product       No
248     COMP0249  STORE_033  2023-01-24          Other       No
255     COMP0256  STORE_036  2023-11-27        Service  Unknown
281     COMP0282  STORE_023  2024-01-09        Product  Unknown
287     COMP0288  STORE_040  2024-03-29        Service       No
305     COMP0306  STORE_017  2023-01-05          Other  Unknown
316     COMP0317  STORE_027  2023-05-04        Product      Yes
318     COMP0319  STORE_033  2024-01-15    Cleanliness  Pending
333     COMP0334  STORE_018  2023-09-28          Other  Unknown
339     COMP0340  STORE_029  2024-04-11        Service       No
349     COMP0350  STORE_013  2023-01-03        Service  Unknown
352     COMP0353  STORE_015  2023-12-20    Cleanliness  Unknown
359     COMP0360  STORE_004  2024-02-03        Service       No
362     COMP0363  STORE_024  2024-04-10    Cleanliness  Unknown
365     COMP0366  STORE_044  2024-05-28        Service  Unknown
370     COMP0371  STORE_028  2024-02-06        Service  Unknown
380     COMP0381  STORE_011  2023-01-29          Other       No
384     COMP0385  STORE_031  2023-03-11          Other      Yes
412     COMP0413  STORE_044  2024-02-14          Other  Pending
425     COMP0426  STORE_017  2024-05-15        Product  Pending
436     COMP0437  STORE_030  2023-01-24        Product  Pending
453     COMP0454  STORE_009  2023-02-01    Cleanliness  Unknown
454     COMP0455  STORE_036  2023-08-09        Product      Yes
466     COMP0467  STORE_044  2023-06-11          Other      Yes
469     COMP0470  STORE_005  2024-04-08    Cleanliness  Unknown
489     COMP0490  STORE_027  2023-03-17          Other  Unknown
493     COMP0494  STORE_001  2023-07-18        Service      Yes

In [4690]:

# تحويل العمود Date إلى نوع datetime مع توحيد الصيغ في DataFrame الصحيح
store_complaints['Date'] = pd.to_datetime(store_complaints['Date'], errors='coerce')

In [4691]:
# عرض أقدم وأحدث تاريخ
earliest_date = store_complaints['Date'].min()
latest_date = store_complaints['Date'].max()

print(f"\nEarliest Date in the data: {earliest_date}")
print(f"Latest Date in the data: {latest_date}")

Earliest Date in the data: 2023-01-03 00:00:00
Latest Date in the data: 2024-06-26 00:00:00

In [4692]:
store_complaints.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 50 entries, 8 to 493
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Complaint_ID    50 non-null     object
 1   Store_ID        50 non-null     object
 2   Date            50 non-null     datetime64[ns]
 3   Complaint_Type  50 non-null     object
 4   Resolved        50 non-null     object
dtypes: datetime64[ns](1), object(4)
memory usage: 2.3+ KB

In [4693]:
# التحقق من وجود مسافات فارغة فقط في الأعمدة النصية
whitespace_rows = store_complaints[store_complaints.select_dtypes(include=['object']).apply(lambda x: x.str.contains('^\s*$', na=False)).any(axis=1)]

# عرض الصفوف التي تحتوي على مسافات فارغة في الأعمدة النصية
print("\nRows with White Spaces in Any Text Column:")
print(whitespace_rows)

Rows with White Spaces in Any Text Column:
Empty DataFrame
Columns: [Complaint_ID, Store_ID, Date, Complaint_Type, Resolved]
Index: []

In [4694]:
store_complaints.to_csv('Cleaned_store_complaints.csv', index=False)

In [4695]:
Cleaned_store_complaints = pd.read_csv('Cleaned_store_complaints.csv')

In [4696]:
Cleaned_store_complaints.shape

(50, 5)